const crypto = require('crypto');
const request = $('Authorize Social Request').first().json;
const profiles = $('Read Social Profiles').all().map(i => i.json);
const rows = $('Read Social Posts').all().map(i => i.json).filter(r => r.post_key);
const response = $input.first().json;
const body = response.body || response;
const channels = Array.isArray(body.data?.channels) && !body.errors ? body.data.channels : [];
const known = {
  edwardjanusz: { page: '61594093026807', channel: '6aa08c72cd8b9c702c31bbbd', host: 'https://www.edwardjanusz.pl/' },
  silverandglass: { page: '61593755021660', channel: '6aa08c72cd8b9c702c31bbbe', host: 'https://www.silverandglass.pl/' }
};
const deny = (error,message) => [{ json: { ok: false, route: 'return', error, message: message || error, published: false } }];
const contentHash = p => crypto.createHash('sha256').update(JSON.stringify([p.profile_key,p.fb_page_id,p.source_url,p.image_url,p.image_sha256,p.caption])).digest('hex');
if (!request.ok) return deny('UNAUTHORIZED');
const safe = rows.filter(r => known[r.profile_key]?.page === r.fb_page_id);
const summary = safe.filter(r => !request.profile_key || r.profile_key === request.profile_key).map(r => ({
  post_key: r.post_key, profile_key: r.profile_key, title: r.source_title, caption: r.caption,
  image_url: r.image_url, content_hash: contentHash(r), status: r.status, approved_at: r.approved_at,
  buffer_post_id: r.buffer_post_id || '', published_url: r.published_url || '', last_error: r.last_error || ''
}));
if (request.operation === 'read') return [{ json: { ok: true, route: 'return',
  profiles: profiles.filter(p => known[p.profile_key]?.page === p.fb_page_id).map(p => ({
    profile_key: p.profile_key, brand: p.brand_name, channel_id: p.buffer_channel_id,
    connected: channels.some(c => c.id === known[p.profile_key].channel && c.service === 'facebook' && c.isDisconnected === false && c.isLocked === false),
    automatic_schedule_enabled: p.posting_enabled === true,
    manual_publishing: 'Polecenie wlasciciela zatwierdza wskazana wersje i publikuje teraz. Kolejnosc, termin i limit dzienny sa ustawieniami domyslnymi.'
  })), posts: summary, approved_count: summary.filter(r => r.status === 'APPROVED').length,
  buffer_read_ok: channels.length > 0, published: false } }];
const matches = safe.filter(r => r.post_key === request.post_key);
if (matches.length !== 1) return deny('SELECT_EXACT_POST_FROM_READ');
const post = matches[0], spec = known[post.profile_key];
const profileMatches = profiles.filter(p => p.profile_key === post.profile_key && p.fb_page_id === spec.page);
if (profileMatches.length !== 1) return deny('PROFILE_NOT_FOUND');
const profile = profileMatches[0];
if (request.profile_key && request.profile_key !== post.profile_key) return deny('PROFILE_MISMATCH');
if (request.operation === 'status') {
  if (!/^[a-zA-Z0-9_-]{8,100}$/.test(post.buffer_post_id || '')) return [{ json: { ok: true, route: 'return', ...summary.find(r => r.post_key === post.post_key), published: post.status === 'PUBLISHED' } }];
  return [{ json: { ok: true, route: 'status', post, channelId: spec.channel } }];
}
if (!['publish_approved','publish_now'].includes(request.operation)) return deny('INVALID_OPERATION');
const directOwnerApproval = request.operation === 'publish_now';
// The current owner message is passed by expression, never generated by the LLM.
const command = String(request.original_message || '').toLowerCase();
const imperative=/(?:^|[^\p{L}])(opublikuj|publikuj|wrzuć|wrzuc)(?=$|[^\p{L}])/u;
const negated=/(?:^|[^\p{L}])(?:nie|nigdy)\s+(?:(?:teraz|jeszcze|proszę|prosze)\s+){0,2}(?:opublikuj|publikuj|wrzuć|wrzuc)(?=$|[^\p{L}])/u;
if(!imperative.test(command)||negated.test(command)||/(?:nie teraz|bez publikacji|tylko (?:podgląd|podglad|odczyt)|na niby|symulacj[\p{L}]*)/u.test(command))return deny('EXPLICIT_PUBLISH_COMMAND_REQUIRED','Nie ma aktualnego polecenia publikacji wskazanego posta.');
if (profile.connection_status !== 'BUFFER_CONNECTED' || profile.buffer_channel_id !== spec.channel || profile.scope !== 'ORGANIC_PHOTO_POSTS_ONLY') return deny('PROFILE_SCOPE_MISMATCH');
if (!channels.some(c => c.id === spec.channel && c.service === 'facebook' && c.isDisconnected === false && c.isLocked === false)) return deny('BUFFER_CHANNEL_NOT_READY','Kanal Facebook w Buffer wymaga naprawy polaczenia.');
if(post.status==='PUBLISHED')return [{json:{ok:true,route:'return',...summary.find(r=>r.post_key===post.post_key),published:!!post.published_url,message:'Ten post jest juz opublikowany. Nie wysylam go drugi raz.'}}];
if(['PUBLISHING','BUFFER_ACCEPTED','UNKNOWN'].includes(post.status)){
  if(/^[a-zA-Z0-9_-]{8,100}$/.test(post.buffer_post_id||''))return [{json:{ok:true,route:'status',post,channelId:spec.channel}}];
  return deny('EXISTING_ATTEMPT_UNCONFIRMED','Ten sam post ma juz rozpoczęta probe publikacji. Sprawdzam jej wynik; nie tworze duplikatu.');
}
const digest=contentHash(post);
if(directOwnerApproval){
  if(!/^[a-f0-9]{64}$/.test(request.expected_content_hash||''))return deny('READ_EXACT_VERSION_FIRST','Odczytaj wskazany post przez read i przekaz content_hash jako expected_content_hash. Nie wymagaj kolejnej zgody Piotra.');
  if(request.expected_content_hash!==digest)return deny('POST_CHANGED_SINCE_READ','Tresc lub zdjecie zmienily sie po odczycie. Pokaz roznice przed publikacja nowej wersji.');
  if(!['APPROVED','DRAFT','NEEDS_REVIEW','PENDING_REVIEW','PENDING_APPROVAL','REVIEW_REQUIRED','READY','REJECTED'].includes(post.status))return deny('POST_STATE_REQUIRES_REVIEW','Sprawdz wynik poprzedniej operacji przed nowa publikacja.');
}else{
  if(post.status!=='APPROVED'||post.approved_by!=='Piotr'||post.approved_hash!==digest||post.caption_hash!==digest)return deny('EXACT_APPROVAL_REQUIRED','Uzyj publish_now dla aktualnego polecenia wlasciciela; odczytaj wersje i content_hash.');
}
if (typeof post.source_url!=='string'||typeof post.image_url!=='string'||!post.source_url.startsWith(spec.host)||!post.image_url.startsWith(spec.host)||!/^[a-f0-9]{64}$/.test(post.image_sha256||'')||typeof post.caption!=='string'||!post.caption.trim()||post.caption.length>12000)return deny('INVALID_APPROVED_MATERIAL');
const today=$now.setZone('Europe/Warsaw').toISODate();
const approval={approved_by:'Piotr',approved_hash:digest,caption_hash:digest,approved_at:directOwnerApproval?new Date().toISOString():post.approved_at,
  review_notes:directOwnerApproval?JSON.stringify({type:'OWNER_COMMAND',execution_id:String($execution.id),command_sha256:crypto.createHash('sha256').update(String(request.original_message||'')).digest('hex'),approved_hash:digest,previous_status:post.status}):post.review_notes};
return [{ json: { ok: true, route: 'publish', post, approval, channelId: spec.channel, today, claim: String($execution.id),
  payload: { query: 'mutation DonaPublish($input: CreatePostInput!) { createPost(input: $input) { __typename ... on PostActionSuccess { post { id text channelId status externalLink sentAt } } ... on MutationError { message } } }',
    variables: { input: { text: post.caption, channelId: spec.channel, schedulingType: 'automatic', mode: 'shareNow', needsApproval: false, saveToDraft: false, metadata: { facebook: { type: 'post' } }, assets: [{ image: { url: post.image_url } }] } } }
} }];
