const crypto = require('crypto');
const request = $('Authorize Social Request').first().json;
const profiles = $('Read Social Profiles').all().map(i => i.json);
const rows = $('Read Social Posts').all().map(i => i.json).filter(r => r.post_key);
const response = $input.first().json;
const body = response.body || response;
const channels = Array.isArray(body.data?.channels) && !body.errors ? body.data.channels : [];
const known = {
  edwardjanusz: { page: '61594093026807', channel: '6aa08c72cd8b9c702c31bbbd', host: 'https://www.edwardjanusz.pl/' },
  silverandglass: { page: '61593755021660', channel: '6aa08c72cd8b9c702c31bbbe', host: 'https://www.silverandglass.pl/' }
};
const deny = error => [{ json: { ok: false, route: 'return', error, published: false } }];
if (!request.ok) return deny('UNAUTHORIZED');
const safe = rows.filter(r => known[r.profile_key]?.page === r.fb_page_id);
const summary = safe.filter(r => !request.profile_key || r.profile_key === request.profile_key).map(r => ({
  post_key: r.post_key, profile_key: r.profile_key, title: r.source_title, caption: r.caption,
  image_url: r.image_url, status: r.status, approved_at: r.approved_at,
  buffer_post_id: r.buffer_post_id || '', published_url: r.published_url || '', last_error: r.last_error || ''
}));
if (request.operation === 'read') return [{ json: { ok: true, route: 'return',
  profiles: profiles.filter(p => known[p.profile_key]?.page === p.fb_page_id).map(p => ({
    profile_key: p.profile_key, brand: p.brand_name, channel_id: p.buffer_channel_id,
    connected: channels.some(c => c.id === known[p.profile_key].channel && c.service === 'facebook' && c.isDisconnected === false && c.isLocked === false),
    automatic_schedule_enabled: p.posting_enabled === true,
    manual_publishing: 'Exact approved post plus explicit owner command only'
  })), posts: summary, approved_count: summary.filter(r => r.status === 'APPROVED').length,
  buffer_read_ok: channels.length > 0, published: false } }];
const matches = safe.filter(r => r.post_key === request.post_key);
if (matches.length !== 1) return deny('SELECT_EXACT_POST_FROM_READ');
const post = matches[0], spec = known[post.profile_key];
const profileMatches = profiles.filter(p => p.profile_key === post.profile_key && p.fb_page_id === spec.page);
if (profileMatches.length !== 1) return deny('PROFILE_NOT_FOUND');
const profile = profileMatches[0];
if (request.profile_key && request.profile_key !== post.profile_key) return deny('PROFILE_MISMATCH');
if (request.operation === 'status') {
  if (!/^[a-zA-Z0-9_-]{8,100}$/.test(post.buffer_post_id || '')) return [{ json: { ok: true, route: 'return', ...summary.find(r => r.post_key === post.post_key), published: post.status === 'PUBLISHED' } }];
  return [{ json: { ok: true, route: 'status', post, channelId: spec.channel } }];
}
if (request.operation !== 'publish_approved') return deny('INVALID_OPERATION');
// The current owner message is passed by expression, never generated by the LLM.
const command = String(request.original_message || '').toLowerCase();
if (!/(?:^|[^\p{L}])(opublikuj|publikuj|wrzuć|wrzuc)(?=$|[^\p{L}])/u.test(command) || /\b(nie|bez|tylko odczyt|test)\b/.test(command)) return deny('EXPLICIT_PUBLISH_COMMAND_REQUIRED');
if (profile.connection_status !== 'BUFFER_CONNECTED' || profile.buffer_channel_id !== spec.channel || profile.scope !== 'ORGANIC_PHOTO_POSTS_ONLY' || profile.approval_policy !== 'APPROVED_EXACT_CONTENT_ONLY' || Number(profile.posts_per_day) !== 1) return deny('PROFILE_SCOPE_MISMATCH');
if (!channels.some(c => c.id === spec.channel && c.service === 'facebook' && c.isDisconnected === false && c.isLocked === false)) return deny('BUFFER_CHANNEL_NOT_READY');
const digest = crypto.createHash('sha256').update(JSON.stringify([post.profile_key,post.fb_page_id,post.source_url,post.image_url,post.image_sha256,post.caption])).digest('hex');
if (post.status !== 'APPROVED' || post.approved_by !== 'Piotr' || post.approved_hash !== digest || post.caption_hash !== digest) return deny('EXACT_APPROVAL_REQUIRED');
const age = Date.now() - Date.parse(post.approved_at);
if (!Number.isFinite(age) || age < 0 || age > 86400000) return deny('APPROVAL_EXPIRED_REVIEW_REQUIRED');
if (!post.source_url.startsWith(spec.host) || !post.image_url.startsWith(spec.host) || !/^[a-f0-9]{64}$/.test(post.image_sha256 || '') || !post.caption || post.caption.length > 12000) return deny('INVALID_APPROVED_MATERIAL');
const today = $now.setZone('Europe/Warsaw').toISODate();
if (post.scheduled_date && post.scheduled_date > today) return deny('POST_SCHEDULED_FOR_FUTURE');
const same = safe.filter(r => r.profile_key === post.profile_key);
if (same.some(r => ['PUBLISHING','BUFFER_ACCEPTED','UNKNOWN'].includes(r.status))) return deny('PREVIOUS_PUBLICATION_UNRESOLVED');
if (same.some(r => r.status === 'PUBLISHED' && r.scheduled_date === today)) return deny('DAILY_LIMIT_REACHED');
// Deterministic head-of-queue selection plus atomic row claim prevents parallel
// requests for different rows from bypassing the one-post-per-brand daily limit.
const next = same.filter(r => r.status === 'APPROVED' && (!r.scheduled_date || r.scheduled_date <= today)).sort((a,b) => String(a.approved_at).localeCompare(String(b.approved_at)) || a.id-b.id)[0];
if (!next || next.id !== post.id) return deny('ANOTHER_APPROVED_POST_IS_FIRST');
return [{ json: { ok: true, route: 'publish', post, channelId: spec.channel, today, claim: String($execution.id),
  payload: { query: 'mutation DonaPublish($input: CreatePostInput!) { createPost(input: $input) { __typename ... on PostActionSuccess { post { id text channelId status externalLink sentAt } } ... on MutationError { message } } }',
    variables: { input: { text: post.caption, channelId: spec.channel, schedulingType: 'automatic', mode: 'shareNow', needsApproval: false, saveToDraft: false, assets: [{ image: { url: post.image_url } }] } } }
} }];
