const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const M=require('../pilot/command-model.js');
const now=Date.parse('2026-09-08T10:00:00Z');
function run(source,records,input=[]){const $=name=>({first:()=>({json:records[name][0]}),item:{json:records[name][0]},all:()=>records[name].map(json=>({json}))});return JSON.parse(JSON.stringify(vm.runInNewContext('(function(){'+source+'})()',{$,$input:{all:()=>input.map(json=>({json})),first:()=>({json:input[0]})},require:n=>{assert.equal(n,'crypto');return crypto;},$execution:{id:'unit-test'}})[0].json));}
const guard=fs.readFileSync('backend/action-guard.js','utf8'),auth=fs.readFileSync('backend/action-auth.js','utf8'),zoho=fs.readFileSync('backend/zoho-normalize.js','utf8');
const sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
function decide(body,r={},a={}){return run(guard,{'Validate Access':[{authorized:true,tenantId:'PM'}],'Workspace Request':[{body}],'Read Social Target':[r],'Read Approval Target':[a]});}
function post(){const r={id:1,post_key:'own',profile_key:'edwardjanusz',fb_page_id:'61594093026807',source_url:'https://www.edwardjanusz.pl/zbior',image_url:'https://www.edwardjanusz.pl/img.jpg',image_sha256:'a'.repeat(64),caption:'Exact original caption',status:'DRAFT'};r.caption_hash=sha(JSON.stringify([r.profile_key,r.fb_page_id,r.source_url,r.image_url,r.image_sha256,r.caption]));return r;}
test('brand filtering keeps unassigned and other brands out of a selected space',()=>{const d={memory:[{id:1,brandId:'probatum'},{id:2,brandId:'silverandglass'},{id:3}]};assert.deepEqual(M.rows(d,'memory','probatum').map(r=>r.id),[1]);assert.equal(M.rows(d,'memory','all').length,3);});
test('brief excludes expired decisions and reports a missing calendar as unknown',()=>{const d={approvals:[{id:'old',status:'REQUESTED',expiresAt:'2026-09-07'},{id:'new',status:'REQUESTED',expiresAt:'2026-09-09'}],tasks:[],socialPosts:[{status:'DRAFT'},{status:'PUBLISHED'}]};const b=M.brief(d,'all',now);assert.equal(b.decisions,2);assert.equal(b.calendarConnected,false);assert.equal(b.meetings.length,0);});
test('Warsaw day boundaries, midnight endings and all-day exclusive ends are correct',()=>{assert.equal(M.day('2026-09-07T23:00:00Z'),'2026-09-08');assert.deepEqual(M.eventDays({date:'2026-09-08',end:'2026-09-09',allDay:true}),{start:'2026-09-08',end:'2026-09-08'});assert.equal(M.eventDays({date:'2026-09-08T10:00:00Z',end:'2026-09-08T22:00:00Z'}).end,'2026-09-08');});
test('brief includes a multi-day event spanning today and excludes cancellation',()=>{const d={calendar:{calendars:[{status:'READ_OK',events:[{id:1,date:'2026-09-07',end:'2026-09-10',allDay:true},{id:2,date:'2026-09-08',end:'2026-09-09',allDay:true,status:'CANCELLED'}]}]}};assert.equal(M.brief(d,'all',now).meetings.length,1);});
test('health distinguishes stale Zoho data, missed tasks and uncertain publication',()=>{const d={tasks:[{id:'a',status:'TODO',date:'2026-09-07'},{id:'b',status:'DONE',date:'2026-09-07'}],socialPosts:[{id:'c',status:'UNKNOWN'}],calendar:{calendars:[{id:'z',status:'READ_OK',checkedAt:'2026-09-08T08:00:00Z'}]}};assert.deepEqual(M.alerts(d,'all',now).map(a=>a.status),['OVERDUE','UNKNOWN','STALE']);});
test('history distinguishes approval from execution and only links recorded publications',()=>{const d={approvals:[{id:1,title:'Email',status:'APPROVED',approvedAt:'2026-09-08T09:00Z'}],socialPosts:[{id:2,title:'Post',status:'PUBLISHED',publishedAt:'2026-09-08T10:00Z',publishedUrl:'https://facebook.com/post'}]};const h=M.history(d);assert.equal(h[0].status,'PUBLISHED');assert.equal(h[1].status,'APPROVED');assert.equal(h[1].url,undefined);});
test('write API requires password, trusted origin and server identity',()=>{const body={haslo:'test-only',operation:'decision'};const f=(b=body,origin='https://dona.probatum.pl')=>run(auth,{'Workspace Request':[{body:b,headers:{origin}}]},[{nazwa:'panel_haslo',wartosc:'test-only'}]);assert.equal(f().authorized,true);assert.equal(f({...body,tenant_id:'OTHER'}).statusCode,403);assert.equal(f(body,'https://evil.example').statusCode,403);assert.equal(f({...body,haslo:'wrong'}).statusCode,401);assert.equal(f({...body,operation:'publish'}).statusCode,400);});
test('social decision checks exact text, image hash, owner page and current status',()=>{const r=post(),b={operation:'decision',kind:'social',id:r.post_key,revision:r.caption_hash,action:'approve'};assert.equal(decide(b,r).status,'APPROVED');assert.equal(decide({...b,action:'reject'},r).status,'REJECTED');for(const changed of [{caption:'changed'},{image_sha256:'b'.repeat(64)},{fb_page_id:'OTHER'},{status:'PUBLISHING'},{status:'PUBLISHED'}])assert.equal(decide(b,{...r,...changed}).ok,false);assert.equal(decide({...b,revision:'b'.repeat(64)},r).error,'stale_content');});
test('approval decisions require tenant, revision, unexpired status and fully reviewable action',()=>{const payload=JSON.stringify({do:'customer@example.com',temat:'Subject',tresc:'Body',konto:'glowne'}),r={id:1,tenant_id:'PM',approval_id:'a',status:'REQUESTED',expires_at:'2099-01-01',payload_preview:payload,payload_hash:'stored',action_type:'send_email_reply_recepcja_poczty'},b={operation:'decision',kind:'approval',action:'approve',id:'a',revision:sha(payload)};assert.equal(decide(b,{},r).status,'APPROVED');assert.equal(decide(b,{},{...r,tenant_id:'OTHER'}).statusCode,404);assert.equal(decide(b,{},{...r,expires_at:'2000-01-01'}).error,'expired');assert.equal(decide(b,{},{...r,action_type:'delete'}).error,'unsupported_action');const unsafe=JSON.stringify({...JSON.parse(payload),hidden_attachment:'unreviewed'});assert.equal(decide({...b,revision:sha(unsafe)},{},{...r,payload_preview:unsafe}).error,'unsupported_action');});
test('Zoho calendar decisions are strict, reviewable and queued only after approval',()=>{const base={calendarId:'own',eventUid:'event@zoho.com',etag:'1692771653044',title:'Spotkanie',start:'2026-09-10T10:00:00+02:00',end:'2026-09-10T10:30:00+02:00',timezone:'Europe/Warsaw',notifyAttendees:0},approve=payload=>{const preview=JSON.stringify(payload),r={id:8,tenant_id:'PM',approval_id:'calendar-a',status:'REQUESTED',expires_at:'2099-01-01',payload_preview:preview,payload_hash:sha(preview),action_type:'ZOHO_EVENT_UPDATE'};return decide({operation:'decision',kind:'approval',action:'approve',id:r.approval_id,revision:sha(preview)},{},r);};const ok=approve(base);assert.equal(ok.status,'APPROVED');assert.equal(ok.executionStatus,'READY');assert.match(ok.title,/zmianę spotkania/);assert.equal(approve({...base,hidden:'x'}).error,'unsupported_action');assert.equal(approve({...base,attendees:['not-an-email']}).error,'unsupported_action');});
test('new knowledge validates brand, text length, request id and source URL',()=>{const b={operation:'save_memory',text:'Original instruction',brandId:'probatum',requestId:'stable-request-123456',sourceUrl:'https://probatum.pl'};assert.equal(decide(b).tags,'brand:probatum');for(const extra of [{brandId:'OTHER'},{text:''},{text:'x'.repeat(6001)},{requestId:'short'},{sourceUrl:'javascript:bad'}])assert.equal(decide({...b,...extra}).ok,false);});
test('Zoho normalization preserves safe mutation metadata and offsets without returning attendees',()=>{const r=run(zoho,{'Select Calendar':[{calendarId:'own',calendarName:'Primary',rangeStart:'2026-09-08',rangeEnd:'2026-10-08'}]},[{statusCode:200,body:{events:[{uid:'recurring',etag:'1234',recurrenceid:'20260908T100000Z',title:'One',dateandtime:{start:'20260908T120000+0200',end:'20260908T123000+0200'},attendees:[{email:'PRIVATE'}]},{uid:'recurring',title:'Two',start:'20260909T100000Z',end:'20260909T103000Z'}]}}]);const e=JSON.parse(r.events_json);assert.equal(r.status,'READ_OK');assert.equal(e.length,2);assert.notEqual(e[0].id,e[1].id);assert.equal(e[0].uid,'recurring');assert.equal(e[0].etag,'1234');assert.equal(e[0].recurrenceId,'20260908T100000Z');assert.equal(e[0].date,'2026-09-08T12:00:00+02:00');assert.doesNotMatch(r.events_json,/PRIVATE/);});
test('Zoho empty-calendar marker is a successful result with zero events',()=>{const r=run(zoho,{'Select Calendar':[{calendarId:'own',calendarName:'Primary',rangeStart:'2026-09-08',rangeEnd:'2026-10-08'}]},[{statusCode:200,body:{events:[{message:'No events found.'}]}}]);assert.equal(r.status,'READ_OK');assert.equal(r.event_count,0);assert.deepEqual(JSON.parse(r.events_json),[]);});
test('Zoho API failure is never rendered as an empty successful calendar',()=>{const r=run(zoho,{'Select Calendar':[{calendarId:'own'}]},[{statusCode:401,body:{error:'EXPIRED'}}]);assert.equal(r.status,'ERROR');assert.equal(r.error_code,'ZOHO_READ_FAILED_401');});
test('generated Zoho Code nodes contain valid JavaScript',()=>{const lines=fs.readFileSync('backend/zoho.workflow.ts','utf8').split('\n');for(const name of ['select','normalize','report']){const prefix='const '+name+' = node(',line=lines.find(v=>v.startsWith(prefix)),spec=JSON.parse(line.slice(prefix.length,-2)),source=spec.config.parameters.jsCode;assert.doesNotMatch(source,/\\\"/);assert.doesNotThrow(()=>new vm.Script('(function(){\n'+source+'\n})'));}});
