(function(){
  'use strict';
  const M=window.DonaBusinessModel;
  const views={today:'Pulpit firmy',orders:'Zlecenia i wyniki',media:'Rolki i materiały',campaigns:'Kampanie',sales:'Sprzedaż',social:'Publikacje Facebook'};
  const descriptions={today:'Zleć pracę Donie. Sprawdź wyniki i sprawy, które potrzebują Twojej decyzji.',orders:'Każde zapisane zlecenie, jego postęp i rezultat.',media:'Zlecaj rolki i odbieraj zapisane materiały.',campaigns:'Cele, terminy, materiały i następne działania.',sales:'Zapytania, oferty i dalszy kontakt z klientami.',social:'Wybierz post i opublikuj go wtedy, kiedy zdecydujesz.'};
  const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safe=v=>{try{const u=new URL(String(v||''));return u.protocol==='https:'?u.href:'';}catch{return '';}};
  const at=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('pl-PL',{timeZone:'Europe/Warsaw',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Brak daty';
  const money=(v,c='PLN')=>v!==null&&v!==''&&v!==undefined&&Number.isFinite(Number(v))?new Intl.NumberFormat('pl-PL',{style:'currency',currency:/^[A-Z]{3}$/.test(c)?c:'PLN',maximumFractionDigits:0}).format(Number(v)):'Nie ustalono';
  const brand=()=>window.DonaCommand?.brand()||'all';
  const brandName=id=>window.DonaModel.brands.find(b=>b.id===id)?.name||'Sprawa firmowa';
  const rows=key=>M.scoped(data,key,brand());
  const badge=s=>'<span class="biz-status '+(M.blocked(s)?'is-blocked':M.finished(s)||s==='PUBLISHED'?'is-done':'')+'">'+E(M.label(s))+'</span>';
  const link=(label,u,cls='secondary')=>safe(u)?'<a class="'+cls+'" href="'+E(safe(u))+'" target="_blank" rel="noopener noreferrer">'+E(label)+' ↗</a>':'';
  const command=(label,text)=>'<button class="secondary" data-prompt="'+E(text)+'">'+E(label)+'</button>';
  const newButton=(kind,label,cls='primary')=>'<button class="'+cls+'" data-business-new="'+kind+'">'+label+'</button>';
  const section=(title,href,content)=>'<section class="biz-section"><div class="biz-section-head"><h2>'+E(title)+'</h2>'+(href?'<a href="'+href+'">Zobacz wszystkie →</a>':'')+'</div>'+content+'</section>';
  const empty=(title,copy,action='')=>'<div class="biz-empty"><h3>'+E(title)+'</h3><p>'+E(copy)+'</p>'+action+'</div>';
  let data=null,demo=false,view='',filter='all',query='',busy=false,lastFeedback='';
  const notices=()=>'<div class="biz-feedback" role="status" '+(lastFeedback?'':'hidden')+'>'+E(lastFeedback)+'</div>';
  const feedback=text=>{lastFeedback=text;document.querySelectorAll('.biz-feedback').forEach(n=>{n.textContent=text;n.hidden=!text;});};
  const everyday=()=>'<section class="biz-everyday" aria-label="Szybkie funkcje"><div><span class="biz-kicker">SZYBKIE FUNKCJE</span><h2>Na co dzień</h2></div><nav>'+[['weather','☀','Pogoda'],['maps','⌖','Mapy'],['mail','✉','Poczta'],['calendar','▦','Kalendarz'],['tools','▦','Wszystkie']].map(([id,symbol,label])=>'<a href="#'+id+'"><span aria-hidden="true">'+symbol+'</span><strong>'+label+'</strong></a>').join('')+'</nav></section>';
  function reason(job){
    if(job.status==='NEEDS_INSPECTION')return 'To zlecenie trwa ponad 30 minut. Dona powinna sprawdzić przebieg przed kolejną płatną próbą.';
    if(/CREDITS/.test(job.errorCode||''))return 'Dostawca wideo zgłosił brak kredytów. Po uzupełnieniu konta zleć Donie dalszy krok.';
    return job.message||job.currentStep||(job.status==='QUEUED'?'Zapisane. Czeka na rozpoczęcie pracy.':job.status==='PROCESSING'?'Produkcja trwa w tle. Możesz zamknąć panel.':job.status==='PREVIEW_READY'?'Materiał jest gotowy do obejrzenia.':'');
  }
  function orderCard(j){return '<article class="biz-order"><div class="biz-order-main"><div class="biz-meta"><span>'+E(j.type==='REEL'?'ROLKA':j.kind==='task'?'ZADANIE':'ZLECENIE')+' · '+E(brandName(j.brandId))+'</span>'+badge(j.status)+'</div><h3>'+E(j.title||j.id)+'</h3><p>'+E(reason(j))+'</p><div class="biz-order-footer"><time>'+E(at(j.updatedAt||j.createdAt||j.date))+'</time><div>'+link('Otwórz materiał',j.resultUrl)+(j.kind==='job'?'<button class="link-button" data-business-job="'+E(j.id)+'">Szczegóły</button>':command('Omów z Doną','Sprawdź zapisane zlecenie '+j.id+': '+j.title+'. Podaj wynik i następny krok.'))+'</div></div></div></article>';}
  function renderHome(){
    const stats=M.metrics(data,brand()),work=M.orders(data,brand()),attention=work.filter(j=>M.blocked(j.status)),active=work.filter(j=>!M.finished(j.status)&&!M.blocked(j.status));
    const meetings=window.DonaModel.calendar(data,brand()).filter(m=>Date.parse(m.end||m.date)>Date.now()).slice(0,3);
    const html='<section class="biz-hero"><div><span class="biz-kicker">DONA · '+E(brandName(brand()))+'</span><h2>Czym dziś się zajmiemy?</h2><p>Jedno polecenie. Zapisane zlecenie. Wynik, do którego możesz wrócić.</p></div><button class="biz-talk" data-chat>Napisz do Dony <span>↗</span></button></section>'+notices()+everyday()+
      '<div class="biz-shortcuts">'+[['reel','01','Stwórz rolkę','Pomysł → gotowy materiał'],['post','02','Przygotuj posty','Treść i materiały marki'],['website','03','Zbuduj stronę','Brief → podgląd strony'],['campaign','04','Zaplanuj kampanię','Cel, kanały i materiały']].map(([k,n,t,c])=>'<button data-business-new="'+k+'"><span>'+n+'</span><strong>'+t+'</strong><small>'+c+'</small><b aria-hidden="true">↗</b></button>').join('')+'</div>'+
      '<div class="biz-metrics">'+[['orders',stats.work,'W trakcie'],['social',stats.drafts,'Posty do przejrzenia'],['orders',stats.blocked,'Wymaga działania'],['clients',stats.clients,'Klienci w widoku']].map(([href,n,t])=>'<a href="#'+href+'"><strong>'+n+'</strong><span>'+t+'</span></a>').join('')+'</div>'+
      (data.workJobsStatus?.ok===false?'<div class="biz-warning">'+E(data.workJobsStatus.message)+'</div>':'')+
      '<div class="biz-two-col"><div>'+section('Dona pracuje','#orders',active.length?active.slice(0,4).map(orderCard).join(''):empty('Możesz zlecić kolejne zadanie','Nie ma otwartych zleceń w odczytanym zakresie.',newButton('task','Zleć pracę')))+section('Ostatnie wyniki','#orders',work.filter(j=>M.finished(j.status)).slice(0,3).map(orderCard).join('')||empty('Tutaj pojawią się wyniki','Gotowe podglądy i zakończone sprawy pozostają zapisane.'))+'</div><div>'+section('Twoja decyzja','#approvals',attention.length?attention.slice(0,3).map(orderCard).join(''):empty('Sprawdź przygotowane materiały','Szkice postów i wiadomości czekają w swoich widokach.','<a href="#social" class="secondary">Otwórz publikacje</a>'))+section('Najbliższe spotkania','#calendar',meetings.length?meetings.map(m=>'<article class="biz-agenda"><time>'+E(at(m.date))+'</time><strong>'+E(m.title)+'</strong><small>'+E(m.location||m.calendarName||'Zoho Calendar')+'</small></article>').join(''):empty('Brak spotkań w tym odczycie','Pełny zakres i czas synchronizacji znajdziesz w kalendarzu.'))+'</div></div>';
    return html;
  }
  function renderOrders(){
    let all=M.orders(data,brand());const counts={all:all.length,active:all.filter(j=>!M.finished(j.status)&&!M.blocked(j.status)).length,ready:all.filter(j=>M.finished(j.status)).length,blocked:all.filter(j=>M.blocked(j.status)).length};
    if(filter==='active')all=all.filter(j=>!M.finished(j.status)&&!M.blocked(j.status));if(filter==='ready')all=all.filter(j=>M.finished(j.status));if(filter==='blocked')all=all.filter(j=>M.blocked(j.status));
    if(query)all=all.filter(j=>(j.title+' '+j.message+' '+j.id).toLocaleLowerCase('pl').includes(query.toLocaleLowerCase('pl')));
    return '<div class="biz-toolbar">'+newButton('task','+ Nowe zlecenie')+'<button class="secondary" data-refresh>Odśwież wyniki</button></div>'+notices()+(data.workJobsStatus?.ok===false?'<div class="biz-warning">'+E(data.workJobsStatus.message)+'</div>':'')+'<div class="biz-filterbar"><div class="biz-tabs">'+[['all','Wszystkie'],['active','W toku'],['ready','Zakończone'],['blocked','Wymaga działania']].map(([k,t])=>'<button data-business-filter="'+k+'" aria-pressed="'+(filter===k)+'">'+t+' <span>'+counts[k]+'</span></button>').join('')+'</div><input type="search" id="businessSearch" aria-label="Szukaj zlecenia" placeholder="Szukaj zlecenia…" value="'+E(query)+'"></div><div class="biz-order-list">'+(all.map(orderCard).join('')||empty('Brak zleceń dla tego widoku','Wybierz inny filtr lub zleć nowe zadanie Donie.'))+'</div>';
  }
  function assetCard(a){const u=safe(a.previewUrl||a.storage||a.sourceUrl);return '<article class="biz-asset"><div class="biz-asset-symbol" aria-hidden="true">'+(/VIDEO|REEL/i.test(a.type)?'▶':/IMAGE/i.test(a.type)?'▧':'↗')+'</div><div><div class="biz-meta"><span>'+E(a.type||'MATERIAŁ')+'</span>'+badge(a.status)+'</div><h3>'+E(a.title||a.id)+'</h3><small>'+E(at(a.updatedAt||a.createdAt))+'</small><div class="biz-actions">'+link('Otwórz',u)+command('Zleć poprawki','Chcę poprawić materiał '+a.id+' — '+a.title+'. Najpierw odczytaj aktualną wersję i zapytaj o zmianę.')+'</div></div></article>';}
  function renderMedia(){const jobs=rows('workJobs'),assets=rows('assets').filter(a=>!/PAGE|WEBSITE|LANDING|SITE/i.test(a.type||''));return '<section class="biz-intro"><div><span class="biz-kicker">TWOJE STUDIO</span><h2>Od pomysłu do materiału</h2><p>Opisz rolkę własnymi słowami albo wybierz do 8 zdjęć prosto z telefonu. Dona zapisze materiały i zleci produkcję bez lektora.</p></div><div class="biz-actions">'+newButton('reel','+ Nowa rolka')+'<button class="secondary" data-business-photos>📷 Rolka ze zdjęć</button></div></section>'+notices()+section('Produkcja rolek','#orders',jobs.length?jobs.slice(0,8).map(j=>orderCard({...j,kind:'job'})).join(''):empty('Zleć pierwszą rolkę','Produkcja działa w tle. Plik pojawi się po potwierdzonym zakończeniu.'))+section('Biblioteka materiałów','',assets.length?'<div class="biz-asset-grid">'+assets.map(assetCard).join('')+'</div>':empty('Brak materiałów w tym widoku','Dona pokaże tu pliki zapisane w rejestrze Twojej firmy.'));}
  function renderCampaigns(){const campaigns=rows('campaigns');return '<div class="biz-toolbar">'+newButton('campaign','+ Nowa kampania')+'<a href="#researchhub" class="secondary">Research i konkurencja</a></div>'+notices()+'<div class="biz-campaign-grid">'+(campaigns.map(c=>'<article class="biz-campaign"><div class="biz-meta"><span>'+E(c.type||'KAMPANIA')+'</span>'+badge(c.status||c.stage)+'</div><h2>'+E(c.name||c.id)+'</h2><p>'+E(c.objective||'Cel nie został jeszcze zapisany.')+'</p><dl><div><dt>Kanały</dt><dd>'+E(c.channels||'Do ustalenia')+'</dd></div><div><dt>Budżet</dt><dd>'+E(money(c.budget))+'</dd></div><div><dt>Termin</dt><dd>'+E(at(c.targetDate))+'</dd></div></dl><div class="biz-next"><span>Następny krok</span><strong>'+E(c.nextAction||'Poproś Donę o aktualizację planu.')+'</strong></div>'+command('Pracuj nad kampanią','Odczytaj kampanię '+c.id+' — '+c.name+'. Pokaż stan i wykonaj możliwy kolejny krok przygotowawczy. Wydatki i publikacje omów ze mną.')+'</article>').join('')||empty('Zaplanuj pierwszą kampanię','Ustal produkt, cel i kanały. Dona pomoże przygotować plan oraz materiały.',newButton('campaign','Zaplanuj kampanię')))+'</div><p class="biz-footnote">Status kampanii pochodzi z jej rejestru. Uruchomienie płatnej reklamy wymaga potwierdzenia z platformy reklamowej.</p>';}
  function renderSales(){const leads=rows('leads'),offers=rows('offers');return '<div class="biz-toolbar">'+newButton('offer','+ Przygotuj ofertę')+'<a href="#clients" class="secondary">Klienci</a><a href="#finance" class="secondary">Finanse i płatności</a></div>'+notices()+'<div class="biz-two-col">'+section('Zapytania','#inquiries',leads.length?leads.slice(0,12).map(l=>'<article class="biz-sale"><div class="biz-meta">'+badge(l.status)+'<time>'+E(at(l.createdAt))+'</time></div><h3>'+E(l.title||l.name)+'</h3><p>'+E(l.description||l.email)+'</p>'+command('Przygotuj kontakt','Odczytaj zapytanie '+l.id+' — '+l.title+'. Przygotuj odpowiedź i następny krok sprzedaży.')+'</article>').join(''):empty('Brak zapisanych zapytań','Nowe kontakty pojawią się po zapisaniu przez Donę lub formularze.'))+section('Oferty','#offers',offers.length?offers.slice(0,12).map(o=>'<article class="biz-sale"><div class="biz-meta">'+badge(o.status)+'<strong>'+E(money(o.amount,o.currency))+'</strong></div><h3>'+E(o.title)+'</h3><p>'+E(o.clientName)+'</p>'+link('Otwórz ofertę',o.url)+command('Omów następny krok','Odczytaj ofertę '+o.id+' — '+o.title+'. Sprawdź status i przygotuj kolejny kontakt.')+'</article>').join(''):empty('Przygotuj ofertę z Doną','Podaj klienta i zakres prac. Zapisane oferty zobaczysz tutaj.'))+'</div>';}
  function renderSocial(){
    const posts=rows('socialPosts'),profiles=(data.socialProfiles||[]).filter(p=>brand()==='all'||p.id===brand());
    const missing=brand()==='probatum'&&!profiles.some(p=>p.id==='probatum'&&p.bufferChannelId);
    return '<div class="biz-toolbar">'+newButton('post','+ Przygotuj posty')+'<a href="#media" class="secondary">Rolki i materiały</a></div>'+notices()+(missing?'<div class="biz-warning"><strong>Profil Probatum czeka na połączenie.</strong> W odczytanym rejestrze nie ma kanału publikacji tej marki. Możesz przygotować treść z Doną.</div>':'')+'<div class="biz-profile-strip">'+profiles.map(p=>'<div><strong>'+E(p.name)+'</strong><span>'+E(p.bufferChannelId?'Kanał zapisany · ostatni odczyt '+at(p.bufferCheckedAt):'Połączenie wymaga sprawdzenia')+'</span></div>').join('')+'</div><p class="biz-footnote">„Publikuj teraz” jest Twoim poleceniem publikacji wyświetlonej treści i zdjęcia. Sam wybierasz post i moment.</p><div class="biz-post-grid">'+(posts.map(p=>'<article class="biz-post">'+(safe(p.image)?'<img src="'+E(safe(p.image))+'" alt="'+E(p.title)+'" loading="lazy" referrerpolicy="no-referrer">':'')+'<div class="biz-post-body"><div class="biz-meta"><span>'+E(brandName(p.profileId))+'</span>'+badge(p.status)+'</div><h2>'+E(p.title)+'</h2><p class="biz-post-text">'+E(p.text)+'</p>'+(p.error?'<p class="biz-warning">'+E(p.error)+'</p>':'')+(p.notes?'<details><summary>Uwagi do materiału</summary><p>'+E(p.notes)+'</p></details>':'')+'<div class="biz-actions">'+(M.drafts(p.status)?'<button class="primary" data-command="publish" data-id="'+E(p.id)+'" data-revision="'+E(p.revision)+'">Publikuj teraz</button><button class="secondary" data-command="revise" data-kind="social" data-id="'+E(p.id)+'">Zleć poprawki</button>':'')+link('Post na Facebooku',p.publishedUrl)+(['PUBLISHING','BUFFER_ACCEPTED','UNKNOWN','UNKNOWN_RESULT','FAILED'].includes(p.status)?command('Sprawdź status','Sprawdź status publikacji posta '+p.id+'. Tylko odczyt, bez ponownego wysyłania.'):'')+link('Źródło',p.source)+'</div></div></article>').join('')||empty('Brak postów w tej przestrzeni','Wybierz markę i poproś Donę o przygotowanie materiałów.',newButton('post','Przygotuj post')))+'</div>';
  }
  function processCards(){
    const plans=rows('processes').filter(p=>p.state?.plan?.tasks?.length);
    if(!plans.length)return '';
    return section('Praca nad Twoją firmą','', '<div class="biz-process-grid">'+plans.map(p=>{
      const ts=p.state.plan.tasks,done=ts.filter(t=>t.status==='VERIFIED').length;
      return '<article class="biz-process-card"><span class="biz-kicker">'+done+' Z '+ts.length+' ETAPÓW Z POTWIERDZONYM WYNIKIEM</span><h3>'+E(p.title)+'</h3><p>'+E(p.currentStep)+'</p><progress max="'+ts.length+'" value="'+done+'" aria-label="Postęp: '+E(p.title)+'"></progress><button class="primary" data-business-process="'+E(p.id)+'">Otwórz plan i zadania →</button></article>';
    }).join('')+'</div>');
  }
  function processDetails(id){
    const p=rows('processes').find(p=>p.id===id);if(!p?.state?.plan)return;
    const d=dialog();d.setAttribute('aria-labelledby','businessDialogTitle');
    const labels={READY:'Można zacząć',WAITING:'Kolejny etap',VERIFIED:'Potwierdzony wynik'};
    d.innerHTML='<header><h2 id="businessDialogTitle">'+E(p.title)+'</h2><button class="icon-button" data-business-close aria-label="Zamknij">×</button></header><p>Wybierz przygotowanie zadania. Odpowiedź zostanie zapisana w rozmowie. Zakończenie etapu wymaga osobnego potwierdzenia wyniku.</p><ol class="biz-process-tasks">'+p.state.plan.tasks.map(t=>'<li><span class="biz-status">'+E(labels[t.status]||'Do sprawdzenia')+'</span><h3>'+E(t.title)+'</h3>'+link('Otwórz wynik',t.resultReference)+(t.status==='READY'&&t.branch&&!['launch','contact','publish'].includes(t.id)?'<button class="primary" data-business-step="'+E(t.id)+'" data-process-id="'+E(p.id)+'">Zleć przygotowanie</button>':'')+'</li>').join('')+'</ol><footer><button class="secondary" data-business-close>Zamknij</button></footer>';
    d.showModal();
  }
  document.addEventListener('click',async e=>{
    const b=e.target.closest('[data-business-process],[data-business-step]');if(!b)return;
    if(b.hasAttribute('data-business-process')){processDetails(b.dataset.businessProcess);return;}
    if(demo){feedback('To podgląd. Zaloguj się, aby wykonać zadanie.');return;}
    if(busy)return;
    const p=rows('processes').find(p=>p.id===b.dataset.processId),t=p?.state?.plan?.tasks.find(t=>t.id===b.dataset.businessStep);
    if(!t||t.status!=='READY'||!t.branch||['launch','contact','publish'].includes(t.id))return;
    const prompt='Pracujesz nad zapisanym procesem '+p.id+': '+p.title+'. Zadanie: '+t.title+'. Aktualny krok: '+p.currentStep+'. Wykonaj możliwą pracę przygotowawczą dostępnymi narzędziami. Najpierw odczytaj aktualne źródła. Nie wymyślaj cen, wyników ani danych. Zwróć konkretny rezultat, źródła i miejsce zapisu. Samo przygotowanie odpowiedzi nie oznacza zakończenia procesu. Bez publikacji, wysyłania wiadomości i uruchamiania reklam.';
    busy=true;b.disabled=true;dialog().close();feedback('Przekazuję zadanie. Wynik znajdziesz w rozmowie z Doną.');
    try{const r=await window.Dona.runBranch(t.branch,p.title,prompt);feedback(!r?'Polecenie nie zostało przyjęte. Sprawdź, czy trwa inne zadanie.':r.ok===false?'Dona zgłosiła problem. Sprawdź odpowiedź w rozmowie.':'Odpowiedź zapisana w rozmowie. Status etapu czeka na weryfikację wyniku.');window.dispatchEvent(new CustomEvent('dona:refresh'));}
    catch{feedback('Nie potwierdzono wyniku. Sprawdź rozmowę przed ponowieniem.');}finally{busy=false;}
  });
  const renderers={today:()=>processCards()+renderHome(),orders:()=>processCards()+renderOrders(),media:renderMedia,campaigns:()=>processCards()+renderCampaigns(),sales:renderSales,social:renderSocial};
  function render(v,d,isDemo){if(view!==v){filter='all';query='';}view=v;data=d;demo=isDemo;window.DonaCommand?.setSnapshot?.(d,isDemo);const root=document.getElementById('viewContent');if(!d){root.innerHTML=empty('Czekam na dane firmy','Po odczycie zobaczysz zlecenia i zapisane wyniki.');return;}root.innerHTML=renderers[v]();}
  function dialog(){let d=document.getElementById('businessDialog');if(!d){d=document.createElement('dialog');d.id='businessDialog';d.className='biz-dialog';document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});}return d;}
  function openForm(kind){
    const d=dialog(),titles={task:'Zleć pracę Donie',reel:'Stwórz rolkę',post:'Przygotuj posty',website:'Zbuduj stronę',campaign:'Zaplanuj kampanię',offer:'Przygotuj ofertę'};
    d.innerHTML='<form id="businessOrderForm"><header><div><span class="biz-kicker">NOWE ZLECENIE</span><h2 id="businessDialogTitle">'+titles[kind]+'</h2></div><button class="icon-button" type="button" data-business-close aria-label="Zamknij">×</button></header>'+(kind==='task'?'<label>Rodzaj zlecenia<select name="kind"><option value="reel">Rolka</option><option value="post">Posty</option><option value="website">Strona WWW</option><option value="campaign">Kampania</option><option value="offer">Oferta</option></select></label>':'<input name="kind" type="hidden" value="'+kind+'">')+'<label>Marka<select name="brand">'+window.DonaModel.brands.filter(b=>b.id!=='all').map(b=>'<option value="'+b.id+'" '+(b.id===(brand()==='all'?'probatum':brand())?'selected':'')+'>'+E(b.name)+'</option>').join('')+'</select></label><label>Co ma przygotować Dona?<textarea name="brief" required minlength="12" maxlength="5000" rows="5" placeholder="Opisz temat, odbiorców i oczekiwany efekt własnymi słowami."></textarea></label>'+(kind==='post'||kind==='task'?'<label data-post-count>Liczba postów<select name="count"><option>1</option><option>3</option><option>5</option><option>7</option></select></label>':'')+'<p>Wynik i odpowiedź Dony pozostaną w rozmowie.'+(kind==='reel'||kind==='task'?' Rolka otrzyma też zapisane zlecenie w widoku „Zlecenia i wyniki”.':'')+'</p><footer><button type="button" class="secondary" data-business-close>Anuluj</button><button type="submit" class="primary">Zleć Donie →</button></footer></form>';const kindSelect=d.querySelector('select[name=kind]'),countGroup=d.querySelector('[data-post-count]');if(kindSelect&&countGroup){const updateCount=()=>{countGroup.style.display=kindSelect.value==='post'?'':'none';};kindSelect.addEventListener('change',updateCount);updateCount();}d.setAttribute('aria-labelledby','businessDialogTitle');d.showModal();d.querySelector('textarea').focus();
  }
  function jobDetails(id){const j=data?.workJobs?.find(j=>j.id===id);if(!j)return;const d=dialog();d.setAttribute('aria-labelledby','businessDialogTitle');d.innerHTML='<header><div><span class="biz-kicker">ZAPISANE ZLECENIE</span><h2 id="businessDialogTitle">'+E(j.title)+'</h2></div><button class="icon-button" data-business-close aria-label="Zamknij">×</button></header>'+badge(j.status)+'<p>'+E(reason(j))+'</p><div class="biz-job-brief">'+E(j.brief)+'</div><dl><dt>Przyjęto</dt><dd>'+E(at(j.createdAt))+'</dd><dt>Ostatnia zmiana</dt><dd>'+E(at(j.updatedAt))+'</dd></dl><footer>'+link('Otwórz materiał',j.resultUrl)+(j.canResume?'<button class="primary" data-business-resume="'+E(j.id)+'">Uruchom zapisane zlecenie</button>':command('Sprawdź z Doną','Odczytaj zapisane zadanie rolki '+j.id+'. Podaj wynik i przyczynę blokady. Bez ponownej płatnej produkcji.'))+'</footer><details><summary>Identyfikator zlecenia</summary><code>'+E(j.id)+'</code></details>';d.showModal();}
  function orderPrompt(values){const selected=window.DonaModel.brands.find(b=>b.id===values.brand);if(!selected)throw new Error('Wybierz markę.');const pre='Marka: '+selected.name+'. Strona: '+selected.website+'. Brief: '+values.brief.trim()+'. ';
    if(values.kind==='reel')return {branch:'marketing',name:'Marketing',text:pre+'Przygotuj scenariusz i storyboard, a następnie zleć rzeczywistą produkcję rolki przez produkuj_rolke. Zapisz zlecenie w tle i podaj jego identyfikator. Nie publikuj.'};
    if(values.kind==='post')return {branch:'marketing',name:'Marketing',text:pre+(['silverandglass','edwardjanusz'].includes(selected.id)?'Przygotuj '+values.count+' postów i zapisz przez przygotuj_posty_do_kolejki dla '+selected.id+'. Korzystaj z prawdziwych materiałów tej marki. Podaj zapisane identyfikatory.':'Przygotuj '+values.count+' szkiców postów. Sprawdź dostępność kolejki tej marki i wyraźnie podaj, gdzie zachowano rezultat.')+' Nie publikuj.'};
    if(values.kind==='website')return {branch:'www',name:'Strony WWW',text:pre+'Przygotuj stronę i jej podgląd. Jeśli brakuje istotnych danych, przeprowadź krótki wywiad. Zapisz wynik i podaj, gdzie go obejrzę. Bez publikacji.'};
    if(values.kind==='campaign')return {branch:'www',name:'Kampanie',text:pre+'Przygotuj kampanię marketingową: cel, kanały, harmonogram, treści i stronę docelową, jeśli potrzebna. Zapisz plan i wskaż następny krok. Bez uruchamiania wydatków ani publikacji.'};
    return {branch:'sprzedaz',name:'Sprzedaż',text:pre+'Przygotuj ofertę na podstawie ustalonego zakresu i cennika. Jeśli brakuje klienta lub ceny, ustal to ze mną. Zapisz ofertę do podglądu. Bez wysyłania.'};
  }
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-business-new],[data-business-photos],[data-business-close],[data-business-job],[data-business-filter],[data-business-resume]');if(!b)return;
    if(b.hasAttribute('data-business-photos')){window.Dona.pickReelPhotos();}else if(b.hasAttribute('data-business-new'))openForm(b.dataset.businessNew);else if(b.hasAttribute('data-business-close'))dialog().close();else if(b.hasAttribute('data-business-job'))jobDetails(b.dataset.businessJob);else if(b.hasAttribute('data-business-filter')){filter=b.dataset.businessFilter;render(view,data,demo);}else if(b.hasAttribute('data-business-resume')){if(demo||busy)return;const j=data?.workJobs?.find(j=>j.id===b.dataset.businessResume&&j.canResume);if(!j)return;dialog().close();busy=true;try{const r=await window.Dona.runBranch('marketing','Zlecenia','Wznów zapisane zadanie '+j.id+' przez sprawdz_zadania_rolek, operacja wznow_zapisane. Nie twórz nowego zadania.');feedback(r?'Sprawdź odpowiedź Dony i aktualny stan zlecenia.':'Dona obsługuje poprzednie polecenie. Spróbuj po jego zakończeniu.');window.dispatchEvent(new CustomEvent('dona:refresh'));}finally{busy=false;}}});
  document.addEventListener('input',e=>{if(e.target.id!=='businessSearch')return;const pos=e.target.selectionStart;query=e.target.value;render(view,data,demo);const n=document.getElementById('businessSearch');n.focus();try{n.setSelectionRange(pos,pos);}catch{}});
  document.addEventListener('submit',async e=>{if(e.target.id!=='businessOrderForm')return;e.preventDefault();if(demo){dialog().close();feedback('To podgląd. Zaloguj się, aby zlecić prawdziwą pracę.');return;}if(busy)return;const values=Object.fromEntries(new FormData(e.target));const task=orderPrompt(values);dialog().close();window.DonaCommand?.selectBrand?.(values.brand);busy=true;feedback('Przekazuję polecenie Donie. Odpowiedź zobaczysz w rozmowie.');try{const r=await window.Dona.runBranch(task.branch,task.name,task.text);feedback(!r?'Dona obsługuje poprzednie polecenie. Nowe nie zostało przyjęte.':r.ok===false?'Dona zgłosiła problem. Szczegóły są w odpowiedzi.':'Dona odpowiedziała. Sprawdź rezultat w rozmowie i zapisane zlecenia.');window.dispatchEvent(new CustomEvent('dona:refresh'));}catch{feedback('Nie potwierdzono przyjęcia polecenia. Sprawdź rozmowę przed ponowieniem.');}finally{busy=false;}});
  window.addEventListener('dona:auth',e=>{if(!e.detail.authenticated&&!e.detail.demo){data=null;lastFeedback='';dialog().close();}});
  window.DonaBusiness={views,descriptions,render,orderPrompt};
})();
