(function(){
'use strict';
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:'';}catch{return '';}};
const when=v=>v?new Date(v).toLocaleString('pl-PL',{timeZone:'Europe/Warsaw',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Brak daty';
const names={READ_OK:'Odczyt potwierdzony',CONFIGURED:'Skonfigurowane',UNKNOWN:'Niepotwierdzone',NOT_CONNECTED:'Niepodłączone',PAUSED:'Wyłączone',DRAFT:'Szkic',APPROVED:'Zatwierdzony',PUBLISHED:'Opublikowany',SCHEDULED:'Zaplanowany',FAILED:'Błąd',ERROR:'Błąd',UNKNOWN_RESULT:'Wynik niepewny'};
const badge=s=>'<span class="signal '+(/ERROR|FAILED|NOT_CONNECTED|PAUSED/.test(s)?'attention':'')+'">'+escape(names[s]||s||'Brak statusu')+'</span>';
const prompt=(label,text)=>'<button class="secondary" data-prompt="'+escape(text)+'">'+escape(label)+'</button>';
let snapshot=null,frame=0,runId=0;const results=[];
function empty(t){return '<div class="centre-empty">'+escape(t)+'</div>';}
function resultCards(){return results.slice(-8).reverse().map(r=>'<article class="result-card"><div class="centre-meta">'+escape(r.label)+'<span>'+escape(r.status==='pending'?'Czekam na odpowiedź':r.status==='error'?'Wynik niepotwierdzony':'Odpowiedź otrzymana')+'</span></div><p>'+escape(r.answer||r.error||'Polecenie wysłano do Dony. Potwierdzenie wykonania pojawi się w odpowiedzi.')+'</p>'+structured(r)+'<small>'+when(r.time)+'</small></article>').join('')||empty('Tu zobaczysz wyniki poleceń z bieżącej sesji. Pełna rozmowa jest w Historii.');}
function structured(r){if(!snapshot||r.status!=='response')return '';const q=r.question||'',b=window.DonaCommand?.brand()||'all';let list=[],source='',href='';if(/kalendarz|spotkani/i.test(q)){list=window.DonaModel.calendar(snapshot,b).slice(0,3).map(e=>({title:e.title,detail:when(e.date)}));source='Spotkania zapisane z Zoho';href='#calendar';}else if(/post|facebook/i.test(q)){list=window.DonaModel.rows(snapshot,'socialPosts',b).slice(0,3).map(e=>({title:e.title,detail:names[e.status]||e.status}));source='Posty w panelu';href='#social';}else if(/poczt|mail/i.test(q)){list=window.DonaModel.rows(snapshot,'mails',b).slice(0,3).map(e=>({title:e.title,detail:e.sender}));source='Zapisane wiadomości';href='#mail';}else return '';return '<div class="data-result"><small>'+escape(source)+' · dane z '+when(snapshot.generatedAt)+'</small>'+list.map(e=>'<p><strong>'+escape(e.title)+'</strong><br>'+escape(e.detail)+'</p>').join('')+'<div class="result-links"><a href="'+href+'" data-close-live>Otwórz widok ↗</a></div></div>';}
function draw(){cancelAnimationFrame(frame);const canvas=document.getElementById('presenceCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let last=0;const token=++runId;
 function step(t){if(token!==runId||!canvas.isConnected)return;if(!document.hidden&&t-last>40){last=t;const size=Math.min(canvas.clientWidth||480,560),dpr=Math.min(devicePixelRatio||1,1.5);if(canvas.width!==Math.round(size*dpr)){canvas.width=Math.round(size*dpr);canvas.height=canvas.width;ctx.setTransform(dpr,0,0,dpr,0,0);}window.drawDonaPresence(ctx,size,reduced?2.7:t/1000,0,220,reduced);}if(!reduced)frame=requestAnimationFrame(step);}
 frame=requestAnimationFrame(step);
}
function connections(d){return (d.connections||[]).map(c=>'<article class="connection-card"><div>'+badge(c.status)+'<h3>'+escape(c.name)+'</h3></div><p>'+escape(c.detail)+'</p><small>Źródło: '+escape(c.source)+' · '+when(d.generatedAt)+'</small></article>').join('')||empty('Nie pobrano stanu połączeń. Odśwież dane.');}
window.DonaCentre={views:{dona:'Przestrzeń Dony',knowledge:'Co Dona wie',connections:'Połączenia',social:'Posty Facebook',activity:'Przebieg pracy'},
 setSnapshot(d){snapshot=d;},
 render(view,d,demo){snapshot=d;const root=document.getElementById('viewContent');cancelAnimationFrame(frame);runId++;d=d||{};const profiles=d.socialProfiles||[],posts=d.socialPosts||[],memory=d.memory||[];const issues=(d.connections||[]).filter(c=>/NOT_CONNECTED|PAUSED|UNKNOWN/.test(c.status));
 if(view==='dona'){
 root.innerHTML='<section class="presence-room"><aside class="presence-side"><span class="centre-eyebrow">TWOJE SPRAWY</span><h2>W zasięgu głosu.</h2><a href="#knowledge" class="presence-link">Co Dona wie <strong>'+memory.length+'</strong></a><a href="#social" class="presence-link">Posty Facebook <strong>'+posts.filter(p=>p.status==='DRAFT').length+' szkiców</strong></a><a href="#connections" class="presence-link">Połączenia <strong>'+issues.length+' do sprawdzenia</strong></a><div class="presence-note">'+(demo?'Podgląd wyglądu. Dane demonstracyjne.':d.generatedAt?'Dane odczytane '+when(d.generatedAt):'Zaloguj się i pobierz dane, aby zobaczyć aktualny stan.')+'</div></aside><div class="presence-main"><span class="centre-eyebrow">DONA · TWOJA ASYSTENTKA</span><canvas id="presenceCanvas" aria-hidden="true"></canvas><h2>Od czego zaczniemy?</h2><p>Porozmawiajmy o tym, co jest teraz ważne.</p><div class="presence-buttons"><button class="primary" data-live>Rozmawiaj z Doną</button><button class="secondary" data-chat>Napisz wiadomość</button></div><span class="presence-mic-note">Mikrofon włącza się po rozpoczęciu rozmowy.</span></div><aside class="presence-side presence-right"><span class="centre-eyebrow">WARTO WIEDZIEĆ</span>'+(issues.length?issues.slice(0,3).map(c=>'<a class="presence-alert" href="#connections"><span>'+escape(c.name)+'</span><strong>'+escape(names[c.status]||c.status)+'</strong><p>'+escape(c.detail)+'</p></a>').join(''):'<p>'+ (d.generatedAt?'Szczegóły dostępności znajdziesz w Połączeniach.':'Stan połączeń czeka na odczyt.')+'</p>')+'<a href="#activity" class="presence-link">Przebieg pracy <span>↗</span></a></aside></section><section class="centre-results"><div class="section-head"><h2>Ostatnie odpowiedzi</h2><a href="#history">Historia rozmowy</a></div><div data-result-feed>'+resultCards()+'</div></section>';draw();
 }else if(view==='connections'){root.innerHTML='<p class="centre-intro">Widzisz źródło i czas odczytu. Konfiguracja połączenia nie oznacza, że wykonano test zewnętrznej usługi.</p><div class="connection-grid">'+connections(d)+'</div><p class="centre-footnote">Pozostałe integracje nie mają jeszcze automatycznego testu dostępności w tym widoku.</p>';
 }else if(view==='knowledge'){
 root.innerHTML='<div class="knowledge-toolbar"><label>Znajdź w pamięci<input id="knowledgeSearch" type="search" placeholder="Marka, projekt, ustalenie…"></label>'+prompt('Dodaj informację','Chcę zapisać nową informację w drugim mózgu. Najpierw zapytaj mnie o jej treść.')+'</div><p class="centre-intro">Wpisy z drugiego mózgu. To część wiedzy Dony — dokumenty i inne bazy nie są tutaj indeksowane. Korektę możesz przekazać w rozmowie.</p><div id="knowledgeList">'+knowledge(memory,'')+'</div>';
 document.getElementById('knowledgeSearch').oninput=e=>{document.getElementById('knowledgeList').innerHTML=knowledge(memory,e.target.value);};
 }else if(view==='social'){
 root.innerHTML='<div class="command-toolbar"><a class="primary" href="#approvals">Sprawdź i zatwierdź posty</a></div><div class="social-profiles">'+profiles.map(p=>'<article class="connection-card"><h3>'+escape(p.name)+'</h3>'+badge(p.connection==='META_NOT_CONNECTED'?'NOT_CONNECTED':p.enabled?'CONFIGURED':'PAUSED')+'<p>'+escape(p.perDay)+' post dziennie · '+escape(p.hour)+':00 · Warszawa</p><small>Ustawienie harmonogramu; publikację potwierdza dopiero wynik i link do posta.</small></article>').join('')+'</div><div class="post-grid">'+(posts.map(p=>'<article class="post-card">'+(safe(p.image)?'<img src="'+escape(safe(p.image))+'" alt="'+escape(p.title)+'" loading="lazy" referrerpolicy="no-referrer">':'')+'<div class="post-body"><div class="centre-meta">'+escape(profiles.find(x=>x.id===p.profileId)?.name||p.profileId)+badge(p.status)+'</div><h3>'+escape(p.title)+'</h3><p>'+escape(p.text)+'</p>'+(p.notes?'<details><summary>Uwagi do materiału</summary><p>'+escape(p.notes)+'</p></details>':'')+'<div class="post-actions">'+(safe(p.source)?'<a class="secondary" href="'+escape(safe(p.source))+'" target="_blank" rel="noopener noreferrer">Zobacz źródło</a>':'')+(p.status==='DRAFT'?'<button class="primary" data-edit-social="'+escape(p.id)+'">Edytuj</button>':'')+prompt('Omów treść','Omów ze mną ten szkic posta dla '+p.profileId+'. Nie publikuj ani nie oznaczaj jako zatwierdzony. Treść:\n'+p.text)+(safe(p.publishedUrl)?'<a class="primary" href="'+escape(safe(p.publishedUrl))+'" target="_blank" rel="noopener noreferrer">Otwórz post</a>':'')+'</div>'+(p.status==='DRAFT'?'<small class="post-disclaimer">Szkic nie jest zatwierdzony do publikacji. Omówienie nie zmienia jego statusu.</small>':'')+'</div></article>').join('')||empty('Nie pobrano postów. Odśwież dane.'))+'</div>';
 }else if(view==='activity'){root.innerHTML='<p class="centre-intro">Odpowiedzi z bieżącej sesji i zadania zapisane w systemie. Otrzymanie odpowiedzi nie jest równoznaczne z wykonaniem zleconej operacji.</p><div data-result-feed>'+resultCards()+'</div><h2 class="centre-subtitle">Zapisane zadania</h2>'+((d.tasks||[]).map(t=>'<article class="result-card"><div class="centre-meta">'+escape(t.title)+badge(t.status)+'</div><p>'+escape(t.description)+'</p><small>'+when(t.date)+'</small></article>').join('')||empty('Brak zapisanych zadań w tym odczycie.'));}
 },clear(){snapshot=null;results.length=0;cancelAnimationFrame(frame);runId++;document.querySelectorAll('[data-result-feed]').forEach(n=>n.textContent='');}};
function knowledge(memory,q){const items=memory.filter(m=>(m.text+' '+m.tags+' '+m.type).toLocaleLowerCase('pl').includes(q.toLocaleLowerCase('pl')));return items.map(m=>'<article class="knowledge-card"><div class="centre-meta">'+escape(m.type||'Wpis')+badge(m.status)+'</div><p>'+escape(m.text)+'</p><small>Źródło: '+escape(m.source)+(m.sourceRef?' · '+escape(m.sourceRef):'')+' · '+when(m.updatedAt)+'</small><div>'+prompt('Przekaż korektę','Chcę skorygować wpis drugiego mózgu '+m.id+'. Obecna treść: '+m.text+'\nNajpierw zapytaj mnie, co zmienić. Nie usuwaj ani nie zapisuj nic przed moją odpowiedzią.')+'</div></article>').join('')||empty(q?'Brak pasujących wpisów.':'Brak wpisów w drugim mózgu dla tej przestrzeni. Dodaj pierwszą informację.');}
window.addEventListener('dona:operation',e=>{const r=e.detail;let existing=results.find(x=>x.id===r.id);if(existing)Object.assign(existing,r);else results.push({...r,time:new Date().toISOString()});while(results.length>20)results.shift();document.querySelectorAll('[data-result-feed]').forEach(n=>n.innerHTML=resultCards());});
document.addEventListener('click',e=>{const button=e.target.closest('[data-edit-social]');if(button)window.DonaCommand?.revise?.('social',button.dataset.editSocial);});
window.addEventListener('dona:auth',e=>{if(!e.detail.authenticated&&!e.detail.demo)window.DonaCentre.clear();});
})();
