(function(){
'use strict';
const M=window.DonaModel,E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:'';}catch{return '';}};
const at=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('pl-PL',{timeZone:'Europe/Warsaw',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Brak daty';
const names={CONFIRMED:'Potwierdzone',SCHEDULED:'Zaplanowane',TODO:'Do wykonania',NEW:'Nowe',ACTIVE:'Aktywne',IN_PROGRESS:'W trakcie',REQUESTED:'Czeka na decyzję',DRAFT:'Szkic',APPROVED:'Zatwierdzone',REJECTED:'Odrzucone',PUBLISHED:'Opublikowano',SAVED:'Zapisano',DONE:'Zakończone',COMPLETED:'Zakończone',READ_OK:'Odczyt potwierdzony',NOT_CONNECTED:'Brak połączenia',ERROR:'Błąd',FAILED:'Błąd',PAUSED:'Wyłączone',OVERDUE:'Po terminie',STALE:'Nieaktualne dane',UNKNOWN:'Do sprawdzenia',RECORDED:'Zapis w systemie'};
const badge=s=>'<span class="signal '+(/ERROR|FAILED|NOT_CONNECTED|PAUSED|OVERDUE|STALE/.test(s)?'attention':'')+'">'+E(names[s]||s||'Niepotwierdzone')+'</span>';
const button=(label,action,extra='')=>'<button class="secondary" data-command="'+action+'" '+extra+'>'+E(label)+'</button>';
const link=(label,href)=>url(href)?'<a class="secondary" href="'+E(url(href))+'" target="_blank" rel="noopener noreferrer">'+E(label)+' ↗</a>':'';
const prompt=(label,text)=>'<button class="secondary" data-prompt="'+E(text)+'">'+E(label)+'</button>';
const empty=t=>'<div class="centre-empty">'+E(t)+'</div>';
let data=null,demo=false,view='',brand='all',calendarMode='week',provider='zoho',cursor=M.day(Date.now()),search='',decisionFilter='all',historyFilter='all';
try{const saved=localStorage.getItem('dona_brand');if(M.brands.some(b=>b.id===saved))brand=saved;}catch{}
const current=()=>M.brands.find(b=>b.id===brand)||M.brands[0];
const scoped=key=>M.rows(data,key,brand);
const brandPreviews={
 probatum:{src:'assets/site-previews/probatum.webp',alt:'Aktualny widok strony głównej Probatum'},
 silverandglass:{src:'assets/site-previews/silverandglass.webp',alt:'Aktualny widok strony głównej Silver & Glass'},
 edwardjanusz:{src:'assets/site-previews/edwardjanusz.webp',alt:'Aktualny widok strony głównej Edward Janusz'}
};
const rerender=()=>window.dispatchEvent(new CustomEvent('dona:rerender'));
const refresh=()=>window.dispatchEvent(new CustomEvent('dona:refresh'));
const toast=t=>{const el=document.getElementById('toast');el.textContent=t;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,8500);};
function brandOptions(value){return M.brands.filter(b=>b.id!=='all').map(b=>'<option value="'+b.id+'" '+(b.id===value?'selected':'')+'>'+E(b.name)+'</option>').join('');}
function setBrand(id){if(!M.brands.some(b=>b.id===id))return;brand=id;try{localStorage.setItem('dona_brand',id);}catch{}document.getElementById('workspaceBrand').value=id;window.Dona.setContext?.(id==='all'?'':id,current().name);rerender();}
function section(title,href,content){return '<section class="command-section"><div class="section-head"><h2>'+E(title)+'</h2>'+(href?'<a href="'+href+'">Otwórz ↗</a>':'')+'</div>'+content+'</section>';}
function itemCard(r,source){return '<article class="result-card"><div class="centre-meta"><strong>'+E(r.title||r.name)+'</strong>'+badge(r.status)+'</div><p>'+E(r.description||r.snippet||r.location||r.clientName||'')+'</p><small>'+E(source||r.source||'Dane panelu')+' · '+at(r.date||r.createdAt)+'</small>'+link('Otwórz',r.url)+'</article>';}
function renderBrief(){const b=M.brief(data,brand),label=b.calendarConnected?'Spotkania dziś: '+b.meetings.length:'Zoho czeka na połączenie';return '<section class="brief-hero"><div><span class="centre-eyebrow">TWÓJ DZIEŃ · '+E(current().name.toUpperCase())+'</span><h2>Najpierw to, co ważne.</h2><p>'+E(label)+'. Materiały do decyzji: '+b.decisions+'. Otwarte zadania: '+b.tasks.length+'.</p><div class="command-actions">'+button('Omów dzień z Doną','discuss-brief')+'<button class="secondary" data-live>Rozmawiaj na żywo</button></div></div><div class="brief-date"><strong>'+new Date().toLocaleDateString('pl-PL',{timeZone:'Europe/Warsaw',day:'numeric'})+'</strong><span>'+new Date().toLocaleDateString('pl-PL',{timeZone:'Europe/Warsaw',month:'long',weekday:'long'})+'</span></div></section><div class="command-metrics"><a href="#approvals"><b>'+b.decisions+'</b><span>Do decyzji</span></a><a href="#calendar"><b>'+(b.calendarConnected?b.meetings.length:'—')+'</b><span>Spotkania Zoho</span></a><a href="#activity"><b>'+b.tasks.length+'</b><span>Otwarte zadania</span></a><a href="#health"><b>'+b.alerts.length+'</b><span>Wymaga uwagi</span></a></div><div class="command-columns">'+section('Najbliższe spotkania','#calendar',b.calendarConnected?(b.meetings.map(e=>itemCard(e,'Zoho Calendar')).join('')||empty('Brak spotkań na dziś w odczytanym zakresie.')):empty('Brak odczytu Zoho. Nie oznacza to, że nie masz spotkań.'))+section('Sprawy do załatwienia','#activity',b.tasks.slice(0,5).map(t=>itemCard(t,'Zapisane zadanie')).join('')||empty('Brak otwartych zadań w tym widoku.'))+'</div>'+section('Poczta wymagająca uwagi','',b.mails.slice(0,5).map(m=>itemCard({...m,description:m.sender+(m.account?' · '+m.account:'')+'\n'+m.snippet},'Zapisana poczta')).join('')||empty('Brak takich wiadomości w odczytanych rekordach. To nie jest potwierdzenie pustej skrzynki.'))+'<p class="centre-footnote">Brief powstaje z danych panelu przy odświeżeniu. Ostatni odczyt: '+at(data?.generatedAt)+'.</p>';}
function decisionCard(r,kind){const social=kind==='social',title=r.title||r.id;return '<article class="decision-card">'+(social&&url(r.image)?'<img src="'+E(url(r.image))+'" alt="'+E(title)+'" loading="lazy" referrerpolicy="no-referrer">':'')+'<div><div class="centre-meta"><span>'+E(social?(M.brands.find(b=>b.id===r.profileId)?.name||r.profileId):(r.type||'Prośba o zgodę'))+'</span>'+badge(r.status)+'</div><h3>'+E(title)+'</h3><p class="decision-excerpt">'+E(social?r.text:r.preview)+'</p><div class="command-actions">'+button('Sprawdź i zdecyduj','review','data-kind="'+kind+'" data-id="'+E(r.id)+'"')+button('Edytuj','revise','data-kind="'+kind+'" data-id="'+E(r.id)+'"')+'</div>'+(r.expiresAt?'<small>Ważne do '+at(r.expiresAt)+'</small>':'')+'</div></article>';}
function renderDecisions(){const approvals=M.pending(data,brand),posts=scoped('socialPosts').filter(p=>p.status==='DRAFT');return '<div class="command-toolbar"><div class="segmented">'+[['all','Wszystkie'],['approval','Wiadomości i działania'],['social','Posty Facebook']].map(([id,name])=>'<button data-decision-filter="'+id+'" aria-pressed="'+(decisionFilter===id)+'">'+name+'</button>').join('')+'</div></div><p class="centre-intro">Sprawdź pełną treść przed decyzją. Zgoda na post dotyczy dokładnego tekstu i zdjęcia. Samo zatwierdzenie nie włącza publikacji.</p><div class="decision-grid">'+((decisionFilter!=='social'?approvals.map(r=>decisionCard(r,'approval')).join(''):'')+(decisionFilter!=='approval'?posts.map(r=>decisionCard(r,'social')).join(''):'' )||empty('Brak aktualnych materiałów do decyzji w tej przestrzeni.'))+'</div>';}
function renderSpaces(){return '<p class="centre-intro">Każda marka ma własny kontekst rozmowy i oznaczone materiały. Sprawy bez przypisania znajdziesz w „Wszystkie sprawy”. To przestrzenie Twojego konta.</p><div class="space-grid">'+M.brands.filter(b=>b.id!=='all').map(b=>{const notes=[...(data?.memory||[]),...(data?.permanentMemory||[])].filter(m=>M.inBrand(m,b.id));const posts=M.rows(data,'socialPosts',b.id),preview=brandPreviews[b.id],website=url(b.website),host=website?new URL(website).hostname:'';return '<article class="space-card"><div class="space-site-preview"><div class="space-site-bar"><i></i><i></i><i></i><span>'+E(host)+'</span></div><img src="'+E(preview.src)+'" alt="'+E(preview.alt)+'" loading="lazy" decoding="async"></div><div class="space-card-content"><span class="centre-eyebrow">TWOJA MARKA</span><h2>'+E(b.name)+'</h2><p>Wpisy wiedzy: '+notes.length+' · Posty: '+posts.length+'</p><div class="command-actions">'+button('Otwórz przestrzeń','select-brand','data-brand="'+b.id+'"')+link('Strona',b.website)+'</div>'+button('Dodaj zasady komunikacji','brand-rule','data-brand="'+b.id+'"')+'</div></article>';}).join('')+'</div>';}
function renderHealth(){const list=M.alerts(data,brand);return '<div class="command-toolbar"><p class="centre-intro">Problemy wykryte w zapisanych danych i stanie połączeń. Widok nie obejmuje jeszcze każdego uruchomienia n8n.</p><button class="secondary" data-refresh>Odśwież stan</button></div>'+ (list.map(a=>'<article class="health-card"><span class="health-dot"></span><div><div class="centre-meta">'+badge(a.status)+'<small>'+at(a.date)+'</small></div><h3>'+E(a.title)+'</h3><p>'+E(a.detail)+'</p><a href="'+a.href+'">Sprawdź szczegóły ↗</a></div></article>').join('')||empty('W tym odczycie nie wykryto problemów. Pozostałe integracje nie były testowane.'));}
function renderKnowledge(){const list=[...scoped('memory'),...scoped('permanentMemory')].filter(m=>(m.text+' '+m.tags+' '+m.source).toLocaleLowerCase('pl').includes(search.toLocaleLowerCase('pl')));return '<div class="command-toolbar"><label class="command-search">Szukaj w wiedzy<input id="commandSearch" type="search" value="'+E(search)+'" placeholder="Ustalenie, projekt, marka…"></label><div class="command-actions">'+button('Dodaj wiedzę','add-knowledge')+button('Dokument lub zdjęcie','upload')+button('Nagraj notatkę','dictate')+'</div></div><p class="centre-intro">Drugi mózg i pamięć projektowa. Wpisy mają źródło i datę. Dokumenty zobaczysz w <a href="#files">Plikach</a>.</p><div id="commandKnowledge">'+(list.map(m=>'<article class="knowledge-card"><div class="centre-meta"><span>'+E(m.type||'Notatka')+' · '+E(M.brands.find(b=>b.id===m.brandId)?.name||'Bez przypisania')+'</span>'+badge(m.status)+'</div><p>'+E(m.text)+'</p><small>'+E(m.source)+' · '+at(m.updatedAt)+'</small>'+link('Źródło',m.sourceRef)+prompt('Omów korektę','Chcę skorygować wpis '+m.id+' z '+m.source+'. Obecna treść: '+m.text+'\nZapytaj, co zmienić, i zachowaj źródło korekty.')+'</article>').join('')||empty(search?'Brak pasujących wpisów.':'Nie ma jeszcze wiedzy przypisanej do tej przestrzeni.'))+'</div>';}
function addDays(key,n){const d=new Date(key+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function renderCalendar(){const events=M.calendar(data,brand,provider),calendars=data?.calendar?.calendars||[],connected=calendars.some(c=>c.status==='READ_OK');const selectedDate=new Date(cursor+'T12:00:00Z'),dow=(selectedDate.getUTCDay()+6)%7;const start=calendarMode==='month'?cursor.slice(0,8)+'01':calendarMode==='week'?addDays(cursor,-dow):cursor;const count=calendarMode==='month'?new Date(selectedDate.getUTCFullYear(),selectedDate.getUTCMonth()+1,0).getUTCDate():calendarMode==='week'?7:1;const end=addDays(start,count);const filtered=events.filter(e=>M.eventDays(e).start<end&&M.eventDays(e).end>=start);const title=selectedDate.toLocaleDateString('pl-PL',{month:'long',year:'numeric',timeZone:'UTC'});let html='<form class="calendar-command" id="calendarCommand"><label>Powiedz DONIE prostymi słowami<input id="calendarCommandText" required maxlength="2000" placeholder="DONA, zablokuj piątek i przygotuj przełożenie spotkania…"></label><button class="primary" type="submit">Przekaż DONIE</button><small>Zmiana terminu i wiadomość do uczestników najpierw wrócą jako plan do zatwierdzenia. Dopiero osobna zgoda uruchamia operację.</small></form><div class="command-toolbar calendar-toolbar"><div class="calendar-title">'+button('‹','calendar-back','aria-label="Poprzedni okres"')+'<h2>'+E(title)+'</h2>'+button('›','calendar-next','aria-label="Następny okres"')+button('Dzisiaj','calendar-today')+'</div><div class="segmented">'+[['day','Dzień'],['week','Tydzień'],['month','Miesiąc']].map(([id,n])=>'<button data-calendar-mode="'+id+'" aria-pressed="'+(calendarMode===id)+'">'+n+'</button>').join('')+'</div></div><div class="calendar-sources"><label>Źródło <select id="calendarProvider"><option value="zoho" '+(provider==='zoho'?'selected':'')+'>Zoho Calendar</option><option value="dona" '+(provider==='dona'?'selected':'')+'>Spotkania zapisane przez Donę</option></select></label>'+link('Otwórz Zoho','https://calendar.zoho.com')+'</div>';
 if(provider==='zoho'&&!connected)html+='<div class="zoho-connect"><div class="zoho-word"><span>Z</span><span>O</span><span>H</span><span>O</span></div><div><h3>Twoje spotkania z Zoho — tutaj.</h3><p>Brakuje autoryzacji konta Zoho. Po połączeniu zobaczysz spotkania, godziny, miejsca i nazwy kalendarzy.</p>'+button('Jak połączyć Zoho','zoho-setup')+'</div></div>';
 else if(provider==='zoho')html+='<p class="centre-intro">Zoho · ostatnia synchronizacja '+at(calendars[0]?.checkedAt)+'. '+(calendars[0]?.rangeStart?'Zakres od '+at(calendars[0].rangeStart)+' do '+at(calendars[0].rangeEnd)+'.':'')+'</p>';
 else html+='<p class="centre-intro">Spotkania zapisane przez agentów Dony. To osobne źródło od Zoho.</p>';
 if(calendarMode!=='day'){const padding=calendarMode==='month'?(new Date(start+'T12:00:00Z').getUTCDay()+6)%7:0;html+='<div class="calendar-scroll"><div class="calendar-grid" role="grid" aria-label="Kalendarz spotkań">'+['Pon','Wt','Śr','Czw','Pt','Sob','Ndz'].map(n=>'<div class="calendar-weekday">'+n+'</div>').join('')+Array.from({length:padding},()=>'<div class="calendar-cell void"></div>').join('')+Array.from({length:count},(_,i)=>{const key=addDays(start,i),items=events.filter(e=>M.eventDays(e).start<=key&&M.eventDays(e).end>=key);return '<button class="calendar-cell '+(key===M.day(Date.now())?'is-today':'')+'" data-calendar-day="'+key+'"><strong>'+Number(key.slice(-2))+'</strong>'+items.slice(0,3).map(e=>'<span class="calendar-event">'+E(e.allDay?'Cały dzień':new Date(e.date).toLocaleTimeString('pl-PL',{timeZone:'Europe/Warsaw',hour:'2-digit',minute:'2-digit'}))+' '+E(e.title)+'</span>').join('')+(items.length>3?'<small>+'+(items.length-3)+' więcej</small>':'')+'</button>';}).join('')+'</div></div>';}
 html+='<h3 class="centre-subtitle">'+(calendarMode==='day'?selectedDate.toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'}):'Spotkania w tym okresie')+'</h3>'+(filtered.map(e=>itemCard({...e,description:(e.allDay?'Cały dzień':at(e.date)+' — '+at(e.end))+'\n'+(e.location||'')},provider==='zoho'?'Zoho · '+e.calendarName:'Dona')).join('')||empty(provider==='zoho'&&!connected?'Spotkania pojawią się po połączeniu konta.':'Brak spotkań w pobranych danych dla wybranego okresu.'));return html;}
function renderActivity(){let list=M.history(data,brand);if(historyFilter!=='all')list=list.filter(r=>historyFilter==='errors'?/ERROR|FAIL|UNKNOWN/.test(r.status):historyFilter==='decisions'?/APPROVED|REJECTED/.test(r.status):/PUBLISHED|SENT|DONE|COMPLETED|SAVED|EXECUTED/.test(r.status));return '<div class="command-toolbar"><div class="segmented">'+[['all','Wszystko'],['decisions','Decyzje'],['results','Rezultaty'],['errors','Błędy']].map(([id,n])=>'<button data-history-filter="'+id+'" aria-pressed="'+(historyFilter===id)+'">'+n+'</button>').join('')+'</div></div><p class="centre-intro">Trwałe wpisy z systemu. „Zatwierdzone” oznacza zapisaną zgodę. Wysłanie lub publikacja mają osobny status.</p><div class="history-timeline">'+(list.map(r=>itemCard(r,r.source)).join('')||empty('Brak zapisanych zdarzeń dla wybranego filtra.'))+'</div>'+section('Zapisane zadania','',scoped('tasks').map(t=>itemCard(t,'Zadanie')).join('')||empty('Brak zadań.'));}
const renderers={today:renderBrief,approvals:renderDecisions,spaces:renderSpaces,health:renderHealth,knowledge:renderKnowledge,calendar:renderCalendar,activity:renderActivity};
window.DonaCommand={views:{today:'Poranny brief',approvals:'Skrzynka decyzji',spaces:'Twoje marki',health:'Centrum usterek',knowledge:'Co Dona wie',calendar:'Kalendarz spotkań',activity:'Historia działań'},render(v,d,isDemo){view=v;data=d;demo=isDemo;window.DonaCentre?.setSnapshot?.(d);if(!d){document.getElementById('viewContent').innerHTML=empty('Dane czekają na odczyt.');return;}document.getElementById('viewContent').innerHTML=renderers[v]();},revise:requestRevision,brand:()=>brand,brandName:()=>current().name,scoped(d){if(brand==='all'||!d)return d;const out={...d};for(const key of ['approvals','leads','offers','clients','meetings','tasks','files','activity','memory','permanentMemory','socialPosts','mails','workHistory'])out[key]=M.rows(d,key,brand);out.socialProfiles=(d.socialProfiles||[]).filter(p=>p.id===brand);return out;},clear(){data=null;dialog.close();dialog.innerHTML='';search='';busy=false;}};
const dialog=document.createElement('dialog');dialog.id='commandDialog';dialog.className='command-dialog';dialog.setAttribute('aria-labelledby','commandDialogTitle');document.body.appendChild(dialog);let busy=false;
function showDialog(title,body,footer=''){dialog.innerHTML='<div class="detail-top"><span class="eyebrow">DONA · '+E(current().name)+'</span><button class="icon-button" data-command="close-dialog" aria-label="Zamknij">×</button></div><h2 id="commandDialogTitle">'+E(title)+'</h2>'+body+'<p id="commandFeedback" role="status"></p>'+footer;dialog.showModal();}
function review(kind,id){const r=(kind==='social'?data?.socialPosts:data?.approvals)?.find(x=>x.id===id);if(!r)return;const social=kind==='social',calendar=/^ZOHO_EVENT_/.test(r.actionType||''),deleting=r.actionType==='ZOHO_EVENT_DELETE';const labels={do:'Odbiorca',to:'Odbiorca',recipient:'Odbiorca',temat:'Temat',subject:'Temat',tresc:'Treść',body:'Treść',konto:'Konto',calendarId:'Kalendarz',eventUid:'Identyfikator wydarzenia',etag:'Wersja wydarzenia',recurrenceId:'Wystąpienie cyklu',recurrenceEditType:'Zakres zmiany cyklu',title:'Tytuł',start:'Początek',end:'Koniec',allDay:'Cały dzień',location:'Miejsce',description:'Opis',attendees:'Uczestnicy',notifyAttendees:'Powiadomienia',timezone:'Strefa czasowa'};showDialog(r.title||'Sprawdź materiał','<div class="decision-full">'+(social&&url(r.image)?'<img src="'+E(url(r.image))+'" alt="'+E(r.title)+'" referrerpolicy="no-referrer">':'')+(social?'<p>'+E(r.text)+'</p>'+link('Oryginalne źródło',r.source):'<dl class="decision-fields">'+Object.entries(r.actionPayload||{}).map(([k,v])=>'<dt>'+E(labels[k]||k)+'</dt><dd>'+E(Array.isArray(v)?v.join(', '):typeof v==='boolean'?(v?'Tak':'Nie'):v)+'</dd>').join('')+'</dl>')+'</div><p class="centre-footnote">'+(social?'Zatwierdzasz to zdjęcie i dokładnie ten tekst. Publikacja pozostaje zależna od połączenia z Meta i harmonogramu.':calendar?'Zatwierdzasz dokładnie tę operację w Zoho. Powiadomienia zostaną wysłane tylko wtedy, gdy karta pokazuje ich włączenie.':'Zapisujesz zgodę na tę treść. Ten przycisk nie wysyła wiadomości. Wykonanie przez agenta ma osobny status.')+'</p><label class="review-check"><input id="reviewedExact" type="checkbox"> '+(calendar?'Sprawdziłem kalendarz, termin i powiadomienia':social?'Sprawdziłem pełną treść i zdjęcie':'Sprawdziłem pełną treść oraz odbiorcę')+'</label>'+(deleting?'<label>Wpisz ANULUJ, aby potwierdzić usunięcie wydarzenia<input id="destructiveConfirm" autocomplete="off" maxlength="6"></label>':'') ,'<div class="command-actions">'+((social||r.canApprove)?'<button class="primary" data-command="decide" data-action="approve" data-kind="'+kind+'" data-revision="'+E(r.revision)+'" data-id="'+E(id)+'">Zatwierdź</button>':'<p>Ten rodzaj operacji wymaga obsługi przez Donę.</p>')+button('Edytuj','revise','data-kind="'+kind+'" data-id="'+E(id)+'"')+button('Odrzuć','decide','data-action="reject" data-kind="'+kind+'" data-revision="'+E(r.revision)+'" data-id="'+E(id)+'"')+'</div>');}
function requestRevision(kind,id,prefill='',dispatched=false){
 const r=(kind==='social'?data?.socialPosts:data?.approvals)?.find(x=>x.id===id);if(!r||!window.DonaFeatures)return;
 const raw=((r.type||'')+' '+(r.actionType||'')).toLocaleLowerCase('pl');let branchId='system',branchName='System';
 if(kind==='social'){branchId='marketing';branchName='Marketing';}else if(/ofert|wycen|sprzeda/.test(raw)){branchId='sprzedaz';branchName='Sprzedaż';}else if(/www|stron/.test(raw)){branchId='www';branchName='WWW';}else if(/mail|email|wiadomo|poczt/.test(raw)){branchId='poczta';branchName='Poczta';}
 const currentText=kind==='social'?r.text:JSON.stringify(r.actionPayload||{tytul:r.title,tresc:r.preview||r.description},null,2);
 if(dialog.open)dialog.close();window.DonaFeatures.openRevision({branchId,branchName,subject:(r.title||r.id)+' · '+id,context:currentText,prefill,dispatched});
}
function requestedSocialRevision(detail){
 if(!data)return;const posts=scoped('socialPosts').filter(p=>p.status==='DRAFT');if(!posts.length){toast('Nie ma obecnie szkicu posta, który można edytować.');return;}
 const raw=String(detail?.text||''),q=raw.toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g,'');let target=null;
 const ordinal=q.match(/\b(pierwsz\w*|drug\w*|trzeci\w*|czwart\w*)\b/);if(ordinal){const index=/pierwsz/.test(ordinal[1])?0:/drug/.test(ordinal[1])?1:/trzeci/.test(ordinal[1])?2:3;target=posts[index]||null;}
 if(!target)target=posts.find(p=>q.includes(String(p.id||'').toLocaleLowerCase('pl'))||String(p.title||'').toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/\s+/).filter(w=>w.length>4).some(w=>q.includes(w)));
 if(!target&&posts.length===1)target=posts[0];
 if(target){requestRevision('social',target.id,raw,true);return;}
 toast('Pokazałam szkice. Powiedz tytuł albo „pierwszy”, „drugi”… i czego chcesz zmienić.');
}
function knowledgeForm(initial=''){showDialog('Dodaj wiedzę','<form id="knowledgeForm"><label>Przypisz do marki<select id="knowledgeBrand"><option value="">Bez przypisania</option>'+brandOptions(brand)+'</select></label><label>Co Dona ma zapamiętać?<textarea id="knowledgeText" rows="7" maxlength="6000" required placeholder="Ustalenie, zasada komunikacji, informacja o firmie…">'+E(initial)+'</textarea></label><label>Źródło — link, jeśli jest<input id="knowledgeSource" type="url" placeholder="https://…"></label><p class="centre-footnote">Zapisuję wpisaną treść i jej źródło. Sam link nie oznacza przeczytania zawartości strony.</p><button class="primary" type="submit">Zapisz w pamięci Dony</button></form>');document.getElementById('knowledgeForm').dataset.requestId=crypto.randomUUID();}
async function decide(n){if(demo){toast('To podgląd. Decyzje zapiszesz po zalogowaniu.');return;}if(busy)return;if(!document.getElementById('reviewedExact').checked){document.getElementById('commandFeedback').textContent='Potwierdź sprawdzenie materiału.';return;}const r=(n.dataset.kind==='social'?data.socialPosts:data.approvals).find(x=>x.id===n.dataset.id);if(!r)return;if(n.dataset.action==='approve'&&r.actionType==='ZOHO_EVENT_DELETE'&&document.getElementById('destructiveConfirm')?.value.trim().toUpperCase()!=='ANULUJ'){document.getElementById('commandFeedback').textContent='Wpisz ANULUJ, aby potwierdzić usunięcie wydarzenia.';return;}if(n.dataset.kind==='social'&&n.dataset.action==='approve'){const photo=dialog.querySelector('.decision-full img');if(!photo||!photo.complete||!photo.naturalWidth){document.getElementById('commandFeedback').textContent='Zdjęcie musi się wczytać przed zatwierdzeniem. Sprawdź źródło materiału.';return;}}busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);const generation=data;try{const result=await window.Dona.request('dona-panel-actions',{operation:'decision',kind:n.dataset.kind,id:r.id,revision:n.dataset.revision,action:n.dataset.action},45000);if(data!==generation||!window.Dona.isAuthenticated())return;if(!result.ok)throw Error('SAVE');dialog.close();toast(result.answer);refresh();}catch(e){if(dialog.open)document.getElementById('commandFeedback').textContent='Nie potwierdzono zapisu. Odśwież dane i sprawdź status przed ponowieniem.';}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function setupZoho(){showDialog('Połączenie Zoho Calendar','<p>Odczyt Zoho jest połączony. Aby Dona mogła dodawać, zmieniać i anulować spotkania, rozszerz połączenie OAuth2 o trzy osobne zakresy zapisu.</p><ol><li>Otwórz integrację w n8n.</li><li>W połączeniu „Zoho Calendar OAuth2” ustaw zakresy: READ, CREATE, UPDATE i DELETE dla wydarzeń oraz READ dla listy kalendarzy.</li><li>Połącz konto ponownie i zaakceptuj pokazane uprawnienia. Każda operacja nadal wróci do Skrzynki decyzji.</li></ol><p>Usunięcie wydarzenia wymaga dodatkowo wpisania słowa ANULUJ. Powiadomienia uczestników są domyślnie wyłączone.</p><div class="command-actions">'+link('Otwórz integrację Zoho','https://pmresearch.app.n8n.cloud/workflow/qLjTnqtyXj1DKq5E')+link('Dokumentacja Zoho','https://www.zoho.com/calendar/help/api/post-create-event.html')+'</div>');}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-live]'))document.getElementById('lclose').click();const f=e.target.closest('[data-decision-filter],[data-calendar-mode],[data-calendar-day],[data-history-filter]');if(f){if(f.dataset.decisionFilter)decisionFilter=f.dataset.decisionFilter;if(f.dataset.calendarMode)calendarMode=f.dataset.calendarMode;if(f.dataset.calendarDay){cursor=f.dataset.calendarDay;calendarMode='day';}if(f.dataset.historyFilter)historyFilter=f.dataset.historyFilter;rerender();return;}const n=e.target.closest('[data-command]');if(!n)return;const a=n.dataset.command;if(a==='review')review(n.dataset.kind,n.dataset.id);else if(a==='revise')requestRevision(n.dataset.kind,n.dataset.id);else if(a==='decide')decide(n);else if(a==='close-dialog'&&!busy)dialog.close();else if(a==='add-knowledge')knowledgeForm();else if(a==='select-brand'){setBrand(n.dataset.brand);location.hash='#today';}else if(a==='brand-rule'){setBrand(n.dataset.brand);knowledgeForm('Zasady komunikacji marki '+current().name+':\n');}else if(a==='zoho-setup')setupZoho();else if(a==='upload'){window.Dona.draft('Materiał dla: '+current().name+'. Przeczytaj go, wskaż co zawiera i co warto zapamiętać.');document.getElementById('clipBtn').click();}else if(a==='dictate'){window.Dona.draft('');document.getElementById('dictBtn').click();toast('Nagraj notatkę w rozmowie. Po dyktowaniu zapisz ją przyciskiem pamięci.');}else if(a==='discuss-brief'){const b=M.brief(data,brand);window.Dona.draft('Omów ze mną dzisiejszy brief dla '+current().name+'. Dane panelu z '+data.generatedAt+': '+JSON.stringify({meetings:b.meetings.map(e=>({title:e.title,date:e.date})),decisions:b.decisions,tasks:b.tasks.slice(0,5).map(t=>({title:t.title,date:t.date})),alerts:b.alerts.map(a=>a.title)})+'. Zacznij od priorytetów, bez wysyłek ani zmian.');}else if(a.startsWith('calendar-')){if(a==='calendar-today')cursor=M.day(Date.now());else{const direction=a==='calendar-next'?1:-1;if(calendarMode==='month'){const d=new Date(cursor.slice(0,8)+'01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+direction);cursor=d.toISOString().slice(0,10);}else cursor=addDays(cursor,direction*(calendarMode==='week'?7:1));}rerender();}});
document.addEventListener('change',e=>{if(e.target.id==='workspaceBrand')setBrand(e.target.value);if(e.target.id==='calendarProvider'){provider=e.target.value;rerender();}});
document.addEventListener('input',e=>{if(e.target.id==='commandSearch'){const pos=e.target.selectionStart;search=e.target.value;rerender();const input=document.getElementById('commandSearch');input.focus();try{input.setSelectionRange(pos,pos);}catch{}}});
document.addEventListener('submit',async e=>{if(e.target.id==='calendarCommand'){e.preventDefault();const text=document.getElementById('calendarCommandText').value.trim();if(!text)return;window.Dona.draft(text);setTimeout(()=>document.getElementById('btn').click(),120);return;}if(e.target.id!=='knowledgeForm')return;e.preventDefault();if(demo){toast('Zapis wiedzy jest dostępny po zalogowaniu.');return;}if(busy)return;const text=document.getElementById('knowledgeText').value.trim(),sourceUrl=document.getElementById('knowledgeSource').value.trim();if(!text)return;if(sourceUrl&&!url(sourceUrl)){document.getElementById('commandFeedback').textContent='Źródło powinno zaczynać się od https://';return;}busy=true;e.target.querySelector('button').disabled=true;const generation=data;try{const result=await window.Dona.request('dona-panel-actions',{operation:'save_memory',text,brandId:document.getElementById('knowledgeBrand').value,sourceUrl,requestId:e.target.dataset.requestId},45000);if(data!==generation||!window.Dona.isAuthenticated())return;if(!result.ok)throw Error('SAVE');dialog.close();toast(result.answer);refresh();}catch{if(dialog.open)document.getElementById('commandFeedback').textContent='Nie potwierdzono zapisu. Sprawdź pamięć po odświeżeniu.';}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}});
window.addEventListener('dona:auth',e=>{if(!e.detail.authenticated&&!e.detail.demo)window.DonaCommand.clear();});
window.addEventListener('dona:request-revision',e=>{if(e.detail?.kind==='social')requestedSocialRevision(e.detail);});
window.addEventListener('DOMContentLoaded',()=>{const selector=document.getElementById('workspaceBrand');selector.innerHTML=M.brands.map(b=>'<option value="'+b.id+'">'+E(b.name)+'</option>').join('');setBrand(brand);});
})();
