(function () {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const iconPaths = {
    headset: '<path d="M4 13a8 8 0 0 1 16 0"/><rect x="2" y="12" width="4" height="7" rx="2"/><rect x="18" y="12" width="4" height="7" rx="2"/><path d="M20 19a3 3 0 0 1-3 3h-3"/>',
    home: '<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
    mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',
    file: '<path d="M14 3H5v18h14V8zM14 3v5h5M8 12h8M8 16h6"/>',
    users: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M21 21v-3a5 5 0 0 0-4-5"/>',
    calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18M7 14h2M12 14h2M7 18h2"/>',
    folder: '<path d="M3 7V5h6l2 2h10v13H3z"/>',
    chart: '<path d="M4 20V10M10 20V4M16 20v-8M22 20H2"/>',
    'check-square': '<rect x="3" y="3" width="18" height="18" rx="3"/><path d="m7 12 3 3 7-7"/>',
    check: '<path d="m5 12 4 4L19 6"/>',
    grid: '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    history: '<path d="M3 10a9 9 0 1 1 1 7M3 4v6h6M12 7v5l3 2"/>',
    settings: '<circle cx="12" cy="12" r="3"/><path d="m10 3-1 3-3 1-3-1-1 4 3 2v2l-2 2 2 4 3-1 2 1 1 3h4l1-3 2-1 3 1 2-4-2-2v-2l2-2-2-4-3 1-3-1-1-3z"/>',
    logout: '<path d="M10 3H4v18h6M9 12h12m-4-4 4 4-4 4"/>',
    menu: '<path d="M4 6h16M4 12h16M4 18h16"/>',
    refresh: '<path d="M20 7a9 9 0 0 0-15-2L2 8m0-5v5h5M4 17a9 9 0 0 0 15 2l3-3m0 5v-5h-5"/>',
    message: '<path d="M21 15a3 3 0 0 1-3 3H8l-5 4V6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3z"/><path d="M7 8h10M7 12h7"/>',
    chevrons: '<path d="m5 7 5 5-5 5m8-10 5 5-5 5"/>',
    close: '<path d="m6 6 12 12M18 6 6 18"/>',
    list: '<path d="M9 6h12M9 12h12M9 18h12M3 6h1M3 12h1M3 18h1"/>',
    paperclip: '<path d="m8 12 7-7a4 4 0 0 1 6 6L10 22a6 6 0 0 1-8-8L13 3m-7 13 9-9a1.5 1.5 0 0 1 2 2l-9 9a1.5 1.5 0 0 1-2-2z"/>',
    bookmark: '<path d="M6 3h12v18l-6-4-6 4z"/>',
    lock: '<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v3"/>',
    search: '<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',
    arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
    clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    globe: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18"/>',
    media: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m10 9 5 3-5 3z"/>',
    wallet: '<rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 9h18m-5 5h2"/>',
    shield: '<path d="m12 3 8 3v6c0 5-8 10-8 10S4 17 4 12V6z"/><path d="m8 12 3 3 5-6"/>'
  };
  const icon = (name) => '<svg viewBox="0 0 24 24" aria-hidden="true">' + (iconPaths[name] || iconPaths.file) + '</svg>';
  const escape = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeUrl = (value) => { try { const u = new URL(String(value)); return u.protocol === 'https:' ? u.href : ''; } catch { return ''; } };
  const el = (tag, text, className) => { const n = document.createElement(tag); if (text !== undefined) n.textContent = text; if (className) n.className = className; return n; };
  const labels = {today:'Dzisiaj',approvals:'Do zatwierdzenia',inquiries:'Zapytania',offers:'Oferty',clients:'Klienci',calendar:'Kalendarz',files:'Pliki',marketing:'Marketing i WWW',tools:'Wszystkie narzędzia',history:'Historia rozmowy',settings:'Ustawienia'};
  Object.assign(labels,window.DonaCentre.views);
  const descriptions = {approvals:'Przejrzyj przygotowane materiały i zdecyduj o kolejnym kroku.',inquiries:'Zapytania zapisane przez Twoje formularze i procesy sprzedażowe.',offers:'Oferty, kwoty i aktualny etap pracy z klientem.',clients:'Historia kontaktu i następny krok dla każdej relacji.',calendar:'Spotkania zapisane przez DONĘ. Pełny kalendarz sprawdzisz w rozmowie.',files:'Dokumenty zarejestrowane w systemie. Pozostałych plików poszuka DONA.',marketing:'Przygotuj treści, materiały i strony z narzędziami, które już masz.',tools:'Wybierz obszar, opisz zadanie i odbierz rezultat w rozmowie.',history:'Twoja dotychczasowa rozmowa z panelu — dostępna także tutaj.',settings:'Twoja przestrzeń, głos i połączenia z obecną DONĄ.'};
  const statusNames = {REQUESTED:'Czeka na decyzję',APPROVED:'Zatwierdzone',REJECTED:'Odrzucone',EXPIRED:'Wygasłe',DRAFT:'Szkic',SENT:'Wysłana',ACCEPTED:'Zaakceptowana',WON:'Wygrana',LOST:'Przegrana',NEW:'Nowe',NOWY:'Nowe',NOWA:'Nowa',QUALIFIED:'Zakwalifikowane',CONFIRMED:'Potwierdzone',CANCELLED:'Odwołane',CANCELED:'Odwołane',DONE:'Zakończone',COMPLETED:'Zakończone',ACTIVE:'Aktywny',AKTYWNY:'Aktywny',OPEN:'Otwarte',TODO:'Do wykonania',DO_ZROBIENIA:'Do wykonania',IN_PROGRESS:'W trakcie',W_TRAKCIE:'W trakcie',WYSLANA:'Wysłana',GOTOWA:'Gotowa',ODPOWIEDZIAL:'Odpowiedział',SCHEDULED:'Zaplanowane',PENDING:'Oczekujące',ERROR:'Błąd',FAILED:'Błąd',NURTURING:'Dalszy kontakt'};
  const state = {view:'today',data:null,loading:false,error:'',filter:'',search:'',demo:window.Dona.isDemo,request:0};
  const fieldLabels = {name:'Nazwa',title:'Temat',email:'E-mail',phone:'Telefon',status:'Status',amount:'Kwota netto',currency:'Waluta',createdAt:'Utworzono',date:'Termin',end:'Zakończenie',clientName:'Klient',nextAction:'Następny krok',nextActionAt:'Termin kontaktu',source:'Źródło',expiresAt:'Ważne do',type:'Rodzaj',description:'Opis',id:'Identyfikator',location:'Miejsce'};
  const done = (status) => /^(DONE|COMPLETED|CANCELLED|CANCELED|ZAKONCZONE|ZAKOŃCZONE|ANULOWANE|WYSLANA|SENT|EXECUTED|REJECTED|EXPIRED)$/i.test(status || '');
  const statusText = (s) => statusNames[String(s).toUpperCase()] || String(s || 'Brak statusu').replace(/_/g,' ').toLowerCase();
  const formatDate = (s, full) => { if (!s) return 'Brak terminu'; const d = new Date(s); return Number.isNaN(+d) ? String(s) : d.toLocaleString('pl-PL', {timeZone:'Europe/Warsaw',day:'numeric',month:'short',...(full ? {hour:'2-digit',minute:'2-digit'} : {})}); };
  const time = (s) => new Date(s).toLocaleTimeString('pl-PL', {timeZone:'Europe/Warsaw',hour:'2-digit',minute:'2-digit'});
  const dayKey = (s) => { const d = new Date(s); return Number.isNaN(+d) ? '' : d.toLocaleDateString('sv-SE',{timeZone:'Europe/Warsaw'}); };
  const badge = (s) => '<span class="status-badge '+(/^(REQUESTED|DRAFT|NEW|NOWY|PENDING)$/i.test(s)?'pending':/^(DONE|COMPLETED|APPROVED|ACCEPTED|CONFIRMED|WON)$/i.test(s)?'done':/^(ERROR|FAILED)$/i.test(s)?'problem':'')+'">'+escape(statusText(s))+'</span>';
  const money = (r) => { if(r.amount === null || r.amount === undefined || r.amount === '') return '—'; const n = Number(r.amount); if(!Number.isFinite(n))return '—'; try{return new Intl.NumberFormat('pl-PL',{style:'currency',currency:r.currency||'PLN',maximumFractionDigits:0}).format(n);}catch{return n.toLocaleString('pl-PL');} };
  const rows = (name) => state.data?.[name] || [];
  const pluralRules = new Intl.PluralRules('pl-PL');
  const plural = (n, one, few, many) => ({one, few, many}[pluralRules.select(n)] || many);
  const pending = () => rows('approvals').filter(r => r.status === 'REQUESTED' && (!r.expiresAt || +new Date(r.expiresAt) > Date.now()));
  const pendingTasks = () => rows('tasks').filter(r => !done(r.status)).sort((a,b) => (+new Date(a.date)||Infinity)-(+new Date(b.date)||Infinity));
  const futureMeetings = () => rows('meetings').filter(r => !/CANCEL/i.test(r.status) && +new Date(r.end||r.date) >= Date.now()).sort((a,b)=>+new Date(a.date)-+new Date(b.date));
  const heading = (title, link, count) => '<div class="section-head"><h2>'+escape(title)+(count===undefined?'':'<span class="count-pill">'+count+'</span>')+'</h2>'+(link?'<a class="link-button" href="#'+link+'">Zobacz wszystkie '+icon('arrow')+'</a>':'')+'</div>';
  const empty = (title, copy, name='folder', action) => '<div class="empty-state"><span>'+icon(name)+'</span><h3>'+escape(title)+'</h3><p>'+escape(copy)+'</p>'+(action?'<button class="secondary" data-prompt="'+escape(action)+'">Zapytaj DONĘ '+icon('arrow')+'</button>':'')+'</div>';
  const compact = (r, collection, name='file') => '<button class="compact-row" data-detail="'+collection+'" data-id="'+escape(r.id)+'"><span class="object-icon">'+icon(name)+'</span><span class="row-content"><span class="row-title">'+escape(r.title||r.name||r.id)+'</span><span class="row-subtitle">'+escape(r.clientName||r.description||statusText(r.status))+'</span></span><span class="row-arrow" aria-hidden="true">›</span></button>';
  function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,6500);}
  function openChat(){ $('app').classList.remove('chat-collapsed');$('app').classList.add('chat-open');$('chatToggle').setAttribute('aria-expanded','true'); }
  function closeChat(){ $('app').classList.remove('chat-open');if(innerWidth>1140)$('app').classList.add('chat-collapsed');$('chatToggle').setAttribute('aria-expanded','false');$('chatToggle').focus(); }
  function draft(text){openChat();window.Dona.draft(text);}
  function demoData(){
    const now=Date.now();const ago=m=>new Date(now-m*60000).toISOString();const later=m=>new Date(now+m*60000).toISOString();
    return {ok:true,generatedAt:new Date().toISOString(),context:{tenantId:'demo',name:'Przykładowa firma',userName:'Piotr',role:'OWNER'},approvals:[
      {id:'demo-approval-1',title:'Wycena projektu mieszkania',clientName:'Anna Kowalska',type:'Odpowiedź na zapytanie',status:'REQUESTED',description:'Przygotowana odpowiedź i lista informacji potrzebnych do wyceny.',preview:'Dzień dobry, Pani Anno. Dziękujemy za wiadomość. Chętnie przygotujemy ofertę projektu mieszkania. Prosimy o przesłanie rzutu i orientacyjnego terminu realizacji.',createdAt:ago(12),expiresAt:later(1440)},
      {id:'demo-approval-2',title:'Oferta dla Nowak Studio',clientName:'Nowak Studio',type:'Oferta',status:'REQUESTED',description:'Gotowa do sprawdzenia',preview:'Projekt wnętrza biura — zakres i harmonogram do zatwierdzenia.',createdAt:ago(45),expiresAt:later(1440)},
      {id:'demo-approval-3',title:'Przypomnienie o ofercie',clientName:'Pracownia Forma',type:'Dalszy kontakt',status:'REQUESTED',description:'Termin kontaktu: dzisiaj',preview:'Dzień dobry, czy mieli Państwo okazję zapoznać się z przesłaną ofertą?',createdAt:ago(80),expiresAt:later(1440)}
    ],leads:[{id:'demo-lead-1',name:'Anna Kowalska',title:'Projekt mieszkania · 68 m²',email:'anna@example.com',status:'NEW',source:'Formularz na stronie',createdAt:ago(30),description:'Projekt mieszkania, salon z kuchnią i dwie sypialnie.'},{id:'demo-lead-2',name:'Michał Nowak',title:'Aranżacja biura',email:'michal@example.com',status:'QUALIFIED',source:'E-mail',createdAt:ago(120),description:'Zapytanie o projekt biura i harmonogram.'},{id:'demo-lead-3',name:'Joanna Wiśniewska',title:'Konsultacja wnętrzarska',email:'joanna@example.com',status:'NEW',createdAt:ago(180),source:'Formularz na stronie'},{id:'demo-lead-4',name:'Pracownia Forma',title:'Projekt lokalu usługowego',email:'biuro@example.com',status:'NEW',createdAt:ago(230),source:'Polecenie'}],offers:[{id:'demo-offer-1',title:'Projekt biura — Nowak Studio',clientName:'Nowak Studio',amount:8900,currency:'PLN',status:'DRAFT',createdAt:ago(140),description:'Projekt funkcjonalny, wizualizacje i dokumentacja.'},{id:'demo-offer-2',title:'Projekt lokalu — Forma',clientName:'Pracownia Forma',amount:12500,currency:'PLN',status:'SENT',createdAt:ago(2800),description:'Projekt wnętrza lokalu usługowego.'}],clients:[{id:'demo-client-1',name:'Nowak Studio',email:'michal@example.com',status:'ACTIVE',nextAction:'Rozmowa o projekcie',nextActionAt:later(80)},{id:'demo-client-2',name:'Pracownia Forma',email:'biuro@example.com',status:'ACTIVE',nextAction:'Omówić przesłaną ofertę',nextActionAt:later(180)},{id:'demo-client-3',name:'Anna Kowalska',email:'anna@example.com',status:'NEW',nextAction:'Uzupełnić zakres projektu'}],meetings:[{id:'demo-meeting-1',title:'Rozmowa o projekcie',clientName:'Nowak Studio',date:later(80),end:later(110),status:'CONFIRMED',location:'Online'}],tasks:[{id:'demo-task-1',title:'Sprawdzić ofertę dla Nowak Studio',description:'Zakres i harmonogram projektu biura',date:later(60),status:'TODO'},{id:'demo-task-2',title:'Przypomnieć się w sprawie oferty',description:'Pracownia Forma',date:later(180),status:'TODO'}],files:[{id:'demo-file-1',title:'Oferta — projekt biura.pdf',type:'Oferta',status:'GOTOWA',createdAt:ago(140)},{id:'demo-file-2',title:'Brief projektu mieszkania.pdf',type:'Brief',status:'GOTOWA',createdAt:ago(200)}],activity:[{id:'demo-event-1',title:'Uporządkowano nowe zapytania',date:ago(15)},{id:'demo-event-2',title:'Uzupełniono historię klienta',date:ago(40)}],meta:{truncated:[]}};
  }
  async function loadData(){
    if(state.loading)return;
    if(state.demo){state.data=Object.assign(demoData(),{memory:[{id:'demo-note',text:'Przykładowa zasada: publikujemy wyłącznie po zatwierdzeniu materiału.',type:'zasada',status:'ACTIVE',tags:'publikacja',source:'Dane demonstracyjne',updatedAt:new Date().toISOString()}],socialProfiles:[],socialPosts:[],connections:[{id:'demo-connection',name:'Przykładowa strona Facebook',status:'NOT_CONNECTED',detail:'Przykład brakującego połączenia. To nie jest odczyt Twojego konta.',source:'Dane demonstracyjne'}]});render();return;}
    if(!window.Dona.isAuthenticated())return;
    const request=++state.request;state.loading=true;state.error='';$('refreshBtn').disabled=true;render();
    try{const result=await window.Dona.request('dona-workspace',{operation:'snapshot'},45000);if(request!==state.request)return;if(result.ok!==true||!result.context||!Array.isArray(result.approvals))throw new Error('INVALID_RESPONSE');state.data=result;}
    catch(e){if(request!==state.request)return;state.error=e.message==='AUTH'?'Zaloguj się ponownie.':'Nie udało się pobrać danych. Rozmowa z DONĄ nadal korzysta z dotychczasowego połączenia.';}
    finally{if(request===state.request){state.loading=false;$('refreshBtn').disabled=false;render();}}
  }
  function navigate(){const name=location.hash.slice(1)||'dona';state.view=labels[name]?name:'today';state.search='';state.filter='';$('app').classList.remove('nav-open');$('navScrim').hidden=true;$('menuToggle').setAttribute('aria-expanded','false');render();$('main').scrollTop=0;}
  function render(){
    document.getElementById("app").classList.toggle("in-presence",state.view==='dona');
    const v=state.view;document.title='DONA — '+labels[v];$('breadcrumbTitle').textContent=labels[v];$('pageTitle').textContent=v==='today'?'Dzień dobry, Piotrze.':labels[v];$('pageEyebrow').textContent=v==='today'?new Date().toLocaleDateString('pl-PL',{timeZone:'Europe/Warsaw',weekday:'long',day:'numeric',month:'long'}).toUpperCase():'TWOJA PRZESTRZEŃ';
    $('pageSubtitle').textContent=v==='today'?(state.data?(pending().length?'Sprawdź przygotowane materiały i zaplanuj kolejny krok.':'Zobacz aktualne sprawy i wybierz, czym dziś zajmie się DONA.'):'Twoje sprawy w jednym miejscu.'):descriptions[v]||'Rozmowa, wiedza i potwierdzone wyniki Twojej Dony.';
    document.querySelectorAll('[data-view]').forEach(n=>{if(n.dataset.view===v)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});
    $('companyName').textContent=state.demo?'Przykładowa firma':state.data?.context?.name||'Probatum';
    $('modeLabel').textContent=state.demo?'DANE PRZYKŁADOWE':'PILOTAŻ';
    ['approvalCount','inquiryCount'].forEach((id,i)=>{$(id).hidden=!state.data;$(id).textContent=String(i?rows('leads').length:pending().length);});
    $('pageAction').innerHTML=v==='offers'?'<button class="primary" data-prompt="Pomóż mi przygotować nową ofertę. Najpierw ustal klienta, zakres i cennik. Bez wysyłania.">Nowa oferta '+icon('arrow')+'</button>':v==='clients'?'<button class="secondary" data-prompt="Chcę dodać klienta do systemu. Pomóż mi ustalić wymagane dane i sprawdź, czy klient już istnieje.">Dodaj klienta</button>':'';
    let banner=state.demo?'<div class="notice demo-bar">To podgląd na przykładowych danych. <a href="./">Zaloguj się do DONY →</a></div>':'';
    if(state.error)banner+='<div class="notice error">'+escape(state.error)+'<button class="link-button" data-refresh>Ponów odczyt</button></div>';
    if(v==='today'&&(state.data?.connections||[]).some(c=>c.status==='NOT_CONNECTED'))banner+='<div class="notice error">Nie wszystkie połączenia są gotowe. <a href="#connections">Sprawdź, co blokuje pracę Dony</a></div>';
    if(state.data?.meta?.truncated?.length)banner+='<div class="notice">Widok obejmuje najnowsze rekordy. Pełnego zakresu poszukaj z DONĄ.</div>';
    $('connectionBanner').innerHTML=banner;
    $('dataStamp').textContent=state.demo?'Dane demonstracyjne':state.data?'Ostatni odczyt: '+formatDate(state.data.generatedAt,true):'Brak potwierdzonego odczytu danych.';
    if(window.DonaCentre.views[v]){window.DonaCentre.render(v,state.data,state.demo);return;}
    const independent=['tools','marketing','settings','history'].includes(v);
    if(!state.data&&!independent){$('viewContent').innerHTML=state.loading?'<div class="skeleton hero" aria-label="Wczytywanie danych"></div><div class="skeleton"></div><div class="skeleton"></div>':empty('Dane czekają na połączenie','Odśwież widok, aby pobrać informacje z DONY. Możesz też rozpocząć rozmowę.','refresh','Sprawdź moje bieżące sprawy. Tylko odczyt, bez zmian.');return;}
    if(v==='today')renderToday();else if(v==='approvals')renderApprovals();else if(v==='tools'||v==='marketing')renderTools(v);else if(v==='settings')renderSettings();else if(v==='history')renderHistory();else renderList();
  }
  function approvalCard(r){return '<article class="approval-card"><div class="approval-head"><span class="object-icon">'+icon('mail')+'</span><div class="approval-content"><div class="card-meta"><span class="eyebrow">'+escape(r.type||'MATERIAŁ DO SPRAWDZENIA')+'</span><time>'+escape(formatDate(r.createdAt,true))+'</time></div><h3>'+escape(r.title)+'</h3><div class="card-person">'+escape(r.clientName||'Sprawa w systemie DONY')+'</div>'+(r.description?'<p class="card-copy">'+escape(r.description)+'</p>':'')+'<div class="draft-excerpt">'+escape(r.preview||'Otwórz szczegóły, aby zobaczyć przygotowany materiał.')+'</div><div class="card-actions"><button class="primary" data-detail="approvals" data-id="'+escape(r.id)+'">Sprawdź materiał '+icon('arrow')+'</button><button class="secondary" data-discuss="approvals" data-id="'+escape(r.id)+'">Omów z DONĄ</button></div></div></div></article>';}
  function renderToday(){
    const approvals=pending(),tasks=pendingTasks(),meetings=futureMeetings(),todayMeetings=meetings.filter(r=>dayKey(r.date)===dayKey(Date.now()));
    let html='<div class="metrics"><div class="metric">'+icon('mail')+'<span><b>'+rows('leads').length+'</b> '+plural(rows('leads').length,'zapytanie','zapytania','zapytań')+' w widoku</span></div><div class="metric">'+icon('file')+'<span><b>'+rows('offers').length+'</b> '+plural(rows('offers').length,'oferta','oferty','ofert')+' w widoku</span></div><div class="metric">'+icon('calendar')+'<span><b>'+todayMeetings.length+'</b> '+plural(todayMeetings.length,'spotkanie','spotkania','spotkań')+' dzisiaj</span></div></div>';
    html+=heading('Do zatwierdzenia','approvals',approvals.length);
    if(approvals.length){html+=approvalCard(approvals[0]);html+=approvals.slice(1,3).map(r=>compact(r,'approvals')).join('');}else html+=empty('Nic nie czeka na Twoją zgodę','Nowe prośby pojawią się tutaj, gdy DONA przygotuje działanie do zatwierdzenia.','check-square');
    html+='<div class="bottom-grid"><section><h2>Najbliższe sprawy</h2>'+(tasks.length?tasks.slice(0,3).map(r=>'<button class="compact-row" data-detail="tasks" data-id="'+escape(r.id)+'"><span class="row-content"><strong class="row-title">'+escape(r.title)+'</strong><span class="row-subtitle">'+escape(formatDate(r.date,true))+'</span></span><span class="row-arrow">›</span></button>').join(''):'<p class="small-empty">Brak otwartych zadań w odczytanych danych.</p>')+'</section><section><h2>Najbliższe spotkanie</h2>'+(meetings[0]?'<button class="meeting" data-detail="meetings" data-id="'+escape(meetings[0].id)+'"><span class="meeting-time">'+escape(time(meetings[0].date))+'</span><span><strong>'+escape(meetings[0].title)+'</strong><small>'+escape(formatDate(meetings[0].date))+' · '+escape(meetings[0].clientName||meetings[0].location||'Spotkanie')+'</small></span></button>':'<p class="small-empty">Nie ma nadchodzących spotkań zapisanych w tym widoku.</p>')+'<button class="link-button" data-prompt="Sprawdź mój kalendarz na dzisiaj i jutro. Tylko odczyt, bez tworzenia ani zmieniania wydarzeń.">Sprawdź kalendarz z DONĄ '+icon('arrow')+'</button></section></div>';
    if(rows('activity').length)html+=heading('Ostatnia aktywność')+rows('activity').slice(0,3).map(r=>'<div class="activity"><span class="check">'+icon('clock')+'</span><span>'+escape(r.title)+'<small>'+escape(formatDate(r.date,true))+'</small></span></div>').join('');
    $('viewContent').innerHTML=html;
  }
  function renderApprovals(){const list=pending();$('viewContent').innerHTML=list.length?list.map(approvalCard).join(''):empty('Wszystko przejrzane','Nie ma aktualnych próśb oczekujących na decyzję. Wygasłe i zakończone zgody nie są tu wyświetlane.','check-square');}
  function listConfig(){return {inquiries:{key:'leads',icon:'mail',empty:'Nie ma jeszcze zapisanych zapytań',prompt:'Sprawdź nowe zapytania od klientów w poczcie. Tylko odczyt, bez wysyłek ani zmian.'},offers:{key:'offers',icon:'file',empty:'Pierwsza oferta jest przed Tobą',prompt:'Pomóż przygotować ofertę dla klienta. Najpierw ustal zakres i właściwy cennik. Bez wysyłania.'},clients:{key:'clients',icon:'users',empty:'Nie ma klientów w odczytanych danych',prompt:'Sprawdź klientów w moim CRM. Tylko odczyt.'},calendar:{key:'meetings',icon:'calendar',empty:'Brak zapisanych spotkań',prompt:'Sprawdź mój kalendarz na najbliższe siedem dni. Tylko odczyt.'},files:{key:'files',icon:'folder',empty:'Nie ma zarejestrowanych dokumentów',prompt:'Pomóż mi znaleźć dokument na Dysku. Zapytaj, czego szukam; bez zmian w plikach.'}}[state.view];}
  function renderList(){
    const c=listConfig(),all=rows(c.key);if(!all.length){$('viewContent').innerHTML=empty(c.empty,'Jeśli informacje są w poczcie lub na Dysku, DONA może pomóc je odszukać.',c.icon,c.prompt);return;}
    const options=[...new Set(all.map(r=>r.status).filter(Boolean))];
    $('viewContent').innerHTML='<div class="toolbar"><label class="search-field">'+icon('search')+'<input id="recordSearch" type="search" placeholder="Szukaj w tym widoku…" aria-label="Szukaj w tym widoku" value="'+escape(state.search)+'"></label><select id="statusFilter" aria-label="Filtr statusu"><option value="">Wszystkie statusy</option>'+options.map(s=>'<option value="'+escape(s)+'"'+(s===state.filter?' selected':'')+'>'+escape(statusText(s))+'</option>').join('')+'</select></div><div id="recordResults"></div>';
    $('recordSearch').addEventListener('input',e=>{state.search=e.target.value;renderRecords();});$('statusFilter').addEventListener('change',e=>{state.filter=e.target.value;renderRecords();});renderRecords();
  }
  function renderRecords(){const c=listConfig();const q=state.search.toLocaleLowerCase('pl');const list=rows(c.key).filter(r=>(!state.filter||r.status===state.filter)&&(!q||[r.name,r.title,r.email,r.clientName,r.description].filter(Boolean).join(' ').toLocaleLowerCase('pl').includes(q)));
    if(!list.length){$('recordResults').innerHTML=empty('Brak pasujących wyników','Zmień frazę lub wybierz inny status.','search');return;}
    const isOffers=c.key==='offers';$('recordResults').innerHTML='<div class="table-wrap"><table class="list-table"><thead><tr><th>'+(c.key==='clients'?'Klient':c.key==='leads'?'Zapytanie':'Nazwa')+'</th><th>'+(isOffers?'Netto':'Status')+'</th><th>'+(isOffers?'Status':'Termin / data')+'</th><th><span class="sr-only">Szczegóły</span></th></tr></thead><tbody>'+list.map(r=>'<tr data-detail="'+c.key+'" data-id="'+escape(r.id)+'" tabindex="0" aria-label="Otwórz: '+escape(r.title||r.name||r.id)+'"><td><strong>'+escape(r.title||r.name||r.id)+'</strong><small>'+escape(r.email||r.clientName||r.nextAction||r.type||'')+'</small></td><td>'+(isOffers?'<span class="amount">'+escape(money(r))+'</span>':badge(r.status))+'</td><td>'+(isOffers?badge(r.status):escape(formatDate(r.date||r.nextActionAt||r.createdAt)))+'</td><td class="row-arrow">›</td></tr>').join('')+'</tbody></table></div>';}
  const tools=[['Poczta','mail','Przeglądaj wiadomości i przygotowuj odpowiedzi.'],['Sprzedaż','chart','Oferty, szanse sprzedaży i kolejny kontakt.'],['Klienci','users','Zbierz ustalenia i przygotuj się do spotkania.'],['Dysk','folder','Szukaj dokumentów i pracuj z plikami.'],['Marketing','chart','Przygotowuj treści i plan komunikacji.'],['WWW','globe','Zlecaj strony i pracę nad kampaniami.'],['Media','media','Pracuj z nagraniami, filmami i grafikami.'],['Research','search','Zlecaj wyszukiwanie i analizę informacji.'],['Pieniądze','wallet','Sprawdzaj koszty i sprawy operacyjne.'],['System','settings','Sprawdzaj dostępne funkcje DONY.'],['Serwis','shield','Zlecaj diagnozę problemów technicznych.']];
  function renderTools(v){$('viewContent').innerHTML='<div class="tool-grid">'+tools.filter(t=>v!=='marketing'||['Marketing','WWW','Media','Research'].includes(t[0])).map(t=>'<article class="tool-card"><span class="object-icon">'+icon(t[1])+'</span><h3>'+escape(t[0])+'</h3><p>'+escape(t[2])+'</p><button class="secondary" data-tool="'+escape(t[0])+'">Zleć zadanie '+icon('arrow')+'</button></article>').join('')+'</div>';}
  function renderSettings(){ $('viewContent').innerHTML='<section class="settings-section"><h2>Twoja przestrzeń</h2><div class="setting-row"><span>Firma<small>'+escape(state.demo?'Przykładowa firma':state.data?.context?.name||'Probatum')+'</small></span><span class="status-badge">Pilotaż właściciela</span></div><div class="setting-row"><span>Dostęp<small>Logowanie jest zapamiętane w tej przeglądarce, jeśli wybrano „Zapamiętaj mnie na tym urządzeniu”. Przycisk Wyloguj usuwa zapis.</small></span><button class="secondary" data-logout>Wyloguj</button></div><div class="setting-row"><span>Dotychczasowy panel<small>Możesz wrócić do wcześniejszego interfejsu.</small></span><a class="secondary" href="../">Otwórz ↗</a></div></section><section class="settings-section"><h2>Rozmowa i głos</h2><div class="setting-row"><span>Odczytywanie odpowiedzi<small>Włącz lub wyłącz głos DONY.</small></span><button class="secondary" id="settingsVoice">'+escape($('voiceBtn').textContent)+'</button></div><div class="setting-row"><span>Tempo głosu<small>Ustawienie używane przez głos przeglądarki.</small></span><button class="secondary" id="settingsRate">'+escape($('rateBtn').textContent)+'</button></div><div class="setting-row"><span>Rozmowa na żywo<small>Korzysta z mikrofonu i dotychczasowej integracji głosowej. Rozliczana według użycia.</small></span><button class="secondary" data-live>Rozmawiaj</button></div></section><section class="settings-section"><h2>Co jest połączone</h2><p>Czat, historia, załączniki, pamięć i głos korzystają z istniejących połączeń DONY. Widoki biznesowe pobierają zapisane dane. Samo otwarcie widoku nie uruchamia agentów ani wysyłek.</p><p>To pilotaż Twojej przestrzeni. Konta kolejnych firm i abonamenty nie są jeszcze uruchomione.</p></section>';
    $('settingsVoice').onclick=()=>{$('voiceBtn').click();renderSettings();};$('settingsRate').onclick=()=>{$('rateBtn').click();renderSettings();};}
  function renderHistory(){const history=window.Dona.history();$('viewContent').innerHTML='<div class="toolbar"><button class="secondary" data-chat>Otwórz rozmowę '+icon('message')+'</button><button class="secondary" data-history-refresh>Wczytaj ponownie</button></div>'+(history.length?'<div class="history-list">'+history.map(r=>'<div class="msg '+(r.role==='user'?'me':'dona')+'"><small>'+(r.role==='user'?'TY':'DONA')+'</small>'+escape(r.text)+'</div>').join('')+'</div>':empty('Historia rozmowy','Po zalogowaniu pojawi się tutaj historia z Twojego obecnego panelu.','history'));}
  function discuss(collection,id){const r=rows(collection).find(x=>x.id===id);if(!r)return;draft('Sprawdź '+(collection==='approvals'?'prośbę o zatwierdzenie':collection==='offers'?'ofertę':'sprawę')+' o identyfikatorze '+r.id+' ('+(r.title||r.name||'')+'). Podsumuj aktualny stan i zaproponuj kolejny krok. Najpierw tylko odczyt — bez wysyłek i zmian.');}
  function showDetail(collection,id){
    const r=rows(collection).find(x=>x.id===id);if(!r)return;const dialog=$('detailDialog');dialog.dataset.collection=collection;dialog.dataset.id=id;
    $('detailType').textContent=({approvals:'DO ZATWIERDZENIA',leads:'ZAPYTANIE',offers:'OFERTA',clients:'KLIENT',tasks:'ZADANIE',meetings:'SPOTKANIE',files:'DOKUMENT'})[collection]||'SZCZEGÓŁY';$('detailTitle').textContent=r.title||r.name||r.id;
    const fields=Object.keys(fieldLabels).filter(k=>r[k]!==undefined&&r[k]!==null&&r[k]!==''&&!['title','name','description','id'].includes(k));
    $('detailBody').innerHTML='<dl class="detail-fields">'+fields.map(k=>'<dt>'+fieldLabels[k]+'</dt><dd>'+escape(k==='status'?statusText(r[k]):k==='amount'?money(r):/At$|^date$|^end$/.test(k)?formatDate(r[k],true):r[k])+'</dd>').join('')+'</dl>'+(r.preview||r.description?'<div class="detail-text">'+escape(r.preview||r.description)+'</div>':'')+(collection==='approvals'?'<p class="detail-note">Otwierasz podgląd prośby. Zatwierdzenie i wykonanie odbywa się przez dotychczasową obsługę zgód DONY.</p>':'');
    $('detailActions').replaceChildren();const link=safeUrl(r.url);if(link){const a=el('a','Otwórz dokument ↗','secondary');a.href=link;a.target='_blank';a.rel='noopener noreferrer';$('detailActions').append(a);}const b=el('button','Omów z DONĄ','primary');b.onclick=()=>{dialog.close();discuss(collection,id);};$('detailActions').append(b);dialog.showModal();
  }
  document.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML=icon(n.dataset.icon));
  $('loginForm').onsubmit=e=>{e.preventDefault();$('pwBtn').click();};
  $('menuToggle').onclick=()=>{const open=$('app').classList.toggle('nav-open');$('navScrim').hidden=!open;$('menuToggle').setAttribute('aria-expanded',String(open));};
  $('navScrim').onclick=()=>{$('app').classList.remove('nav-open');$('navScrim').hidden=true;$('menuToggle').setAttribute('aria-expanded','false');};
  $('chatToggle').onclick=()=>{openChat();$('inp').focus();};$('chatClose').onclick=closeChat;$('refreshBtn').onclick=loadData;$('detailClose').onclick=()=>$('detailDialog').close();
  document.addEventListener('click',e=>{const n=e.target.closest('[data-prompt],[data-tool],[data-detail],[data-discuss],[data-refresh],[data-chat],[data-live],[data-logout],[data-history-refresh]');if(!n)return;
    if(n.hasAttribute('data-prompt'))draft(n.dataset.prompt);else if(n.hasAttribute('data-tool')){window.Dona.branch(n.dataset.tool);openChat();}else if(n.hasAttribute('data-detail'))showDetail(n.dataset.detail,n.dataset.id);else if(n.hasAttribute('data-discuss'))discuss(n.dataset.discuss,n.dataset.id);else if(n.hasAttribute('data-refresh'))loadData();else if(n.hasAttribute('data-chat'))openChat();else if(n.hasAttribute('data-live'))$('golive').click();else if(n.hasAttribute('data-logout')){if(state.demo)location.href='./';else window.Dona.logout();}else if(n.hasAttribute('data-history-refresh')){if(state.demo)toast('Historia jest dostępna po zalogowaniu.');else{window.Dona.refreshHistory();renderHistory();}}});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('tr[data-detail]'))e.target.click();if(e.key==='Escape'){$('app').classList.remove('nav-open');$('navScrim').hidden=true;$('menuToggle').setAttribute('aria-expanded','false');}});
  function syncChatButton(){const visible=innerWidth>1140?!$('app').classList.contains('chat-collapsed'):$('app').classList.contains('chat-open');$('chatToggle').setAttribute('aria-expanded',String(visible));}
  window.addEventListener('resize',syncChatButton);syncChatButton();
  window.addEventListener('hashchange',navigate);
  window.addEventListener('dona:open-chat',openChat);
  window.addEventListener('dona:notice',e=>toast(e.detail));
  window.addEventListener('dona:message',()=>{$('assistant').classList.toggle('has-messages',window.Dona.history().length>0);if(state.view==='history')renderHistory();});
  window.addEventListener('dona:phase',e=>{$('assistantStatus').textContent=state.demo?'Podgląd interfejsu':/czekam|zlecenie|prac/i.test(e.detail||'')?'Czekam na wynik z systemu':'Rozmowa z DONĄ';});
  window.addEventListener('dona:auth',e=>{if(e.detail.authenticated||e.detail.demo)loadData();else{state.request++;state.data=null;state.loading=false;state.error='';$('refreshBtn').disabled=false;$('detailDialog').close();$('assistant').classList.remove('has-messages');render();}});
  const observer=new MutationObserver(()=>{$('assistant').classList.toggle('has-messages',$('log').children.length>0);if(state.view==='history')renderHistory();});observer.observe($('log'),{childList:true});
  navigate();if(state.demo){$('assistantStatus').textContent='Podgląd interfejsu';loadData();}else if(window.Dona.isAuthenticated())loadData();
})();
