import json
from pathlib import Path
r=Path(__file__).resolve().parents[1];nodes=[]
def add(var,name,kind,version,params,**extra):
    spec={'type':'n8n-nodes-base.'+kind,'version':version,'config':{'name':name,'parameters':params,**extra},'output':[{'apiBase':'https://calendar.zoho.com','calendarId':'sample-calendar','calendarName':'Sample Calendar','range':'{}','events_json':'[]','tenant_id':'PM','provider':'zoho','calendar_id':'sample-calendar','calendar_name':'Sample Calendar','status':'READ_OK','checked_at':'2026-09-08T12:00:00Z','error_code':'','range_start':'2026-09-08T00:00:00Z','range_end':'2026-10-08T00:00:00Z'}]};nodes.append((var,spec))
add('manual','Connect and Test Zoho','manualTrigger',1,{})
add('schedule','Every 15 Minutes','scheduleTrigger',1.3,{'rule':{'interval':[{'field':'minutes','minutesInterval':15}]}})
add('config','Zoho Configuration','code',2,{'mode':'runOnceForAllItems','jsCode':"return [{json:{apiBase:'https://calendar.zoho.com',calendarIds:[]}}];"},notes='Set the correct Zoho data centre (e.g. calendar.zoho.eu for an EU account). Select calendar UIDs in calendarIds; empty array selects the single default calendar after authenticated discovery. This workflow remains inactive until OAuth is connected and a live read is verified.')
http={'method':'GET','authentication':'genericCredentialType','genericAuthType':'oAuth2Api','options':{'timeout':20000,'redirect':{'redirect':{'followRedirects':False}},'response':{'response':{'responseFormat':'json','fullResponse':True,'neverError':True}}}}
add('calendars','Read Zoho Calendars','httpRequest',4.4,{**http,'url':"={{ $('Zoho Configuration').first().json.apiBase + '/api/v1/calendars' }}",'sendQuery':True,'queryParameters':{'parameters':[{'name':'category','value':'own'}]}},credentials={'oAuth2Api':{'name':'Zoho Calendar OAuth2'}},notes='Create Generic OAuth2 API credential. Authorization Code; regional accounts.zoho.com/oauth/v2/auth and /token URLs; Authentication Body; scope ZohoCalendar.calendar.READ,ZohoCalendar.event.READ; auth query access_type=offline&prompt=consent. Register the n8n OAuth redirect URL displayed in the credential as a Server-based Application at api-console.zoho.com. Bind the SAME credential to Read Zoho Events. Never put tokens into node parameters. Official instructions: https://www.zoho.com/calendar/help/api/oauth2-user-guide.html')
select=r"""const cfg=$('Zoho Configuration').first().json;
if(!/^https:\/\/calendar\.zoho\.(com|eu|in|com\.au|com\.cn|jp|ca|sa)$/.test(cfg.apiBase))throw new Error('INVALID_ZOHO_REGION');
const raw=$input.first().json,b=raw.body||raw;if((raw.statusCode&&raw.statusCode!==200)||!Array.isArray(b.calendars))throw new Error('ZOHO_CALENDARS_READ_FAILED');
const ids=Array.isArray(cfg.calendarIds)?cfg.calendarIds:[];
const selected=ids.length?b.calendars.filter(c=>ids.includes(c.uid)):b.calendars.filter(c=>c.isdefault===true);
if(!selected.length||(!ids.length&&selected.length!==1))throw new Error('SELECT_ZOHO_CALENDAR');
const start=$now.toUTC().startOf('day'),end=start.plus({days:30});
return selected.map(c=>({json:{apiBase:cfg.apiBase,calendarId:String(c.uid),calendarName:String(c.name),range:JSON.stringify({start:start.toFormat("yyyyMMdd'T'HHmmss'Z'"),end:end.toFormat("yyyyMMdd'T'HHmmss'Z'")}),rangeStart:start.toISO(),rangeEnd:end.toISO()}}));"""
add('select','Select Calendar','code',2,{'mode':'runOnceForAllItems','jsCode':select})
add('events','Read Zoho Events','httpRequest',4.4,{**http,'url':"={{ $('Select Calendar').item.json.apiBase + '/api/v1/calendars/' + encodeURIComponent($('Select Calendar').item.json.calendarId) + '/events' }}",'sendQuery':True,'queryParameters':{'parameters':[{'name':'range','value':"={{ $('Select Calendar').item.json.range }}"},{'name':'byinstance','value':'true'},{'name':'timezone','value':'UTC'}]}},credentials={'oAuth2Api':{'name':'Zoho Calendar OAuth2'}},notes='Read only. 30-day range; recurrence expanded by Zoho. Times requested in UTC and displayed in Europe/Warsaw by the panel.',onError='continueRegularOutput')
add('normalize','Normalize Zoho Events','code',2,{'mode':'runOnceForEachItem','jsCode':(r/'backend/zoho-normalize.js').read_text().replace('$input.first().json','$json').replace('return [{json:{tenant_id:', 'return {json:{tenant_id:').replace('range_end:request.rangeEnd}}];','range_end:request.rangeEnd}};')})
values={k:'={{ $json.'+k+' }}' for k in ['tenant_id','provider','calendar_id','calendar_name','events_json','status','checked_at','error_code','range_start','range_end']}
add('save','Save Calendar Snapshot','dataTable',1.1,{'resource':'row','operation':'upsert','dataTableId':{'__rl':True,'mode':'id','value':'lOnEaEQ8varOsmdt'},'matchType':'allConditions','filters':{'conditions':[{'keyName':'tenant_id','condition':'eq','keyValue':'PM'},{'keyName':'provider','condition':'eq','keyValue':'zoho'},{'keyName':'calendar_id','condition':'eq','keyValue':'={{ $json.calendar_id }}'}]},'columns':{'mappingMode':'defineBelow','value':values,'schema':[{'id':k,'displayName':k,'type':'string','display':True,'required':False,'defaultMatch':False,'canBeUsedToMatch':True} for k in values]}})
add('report','Zoho Sync Summary','code',2,{'mode':'runOnceForAllItems','jsCode':"return [{json:{ok:$input.all().every(i=>i.json.status==='READ_OK'),calendars:$input.all().map(i=>({id:i.json.calendar_id,status:i.json.status,checkedAt:i.json.checked_at}))}}];"})
lines=["import { workflow, node, trigger, newCredential } from '@n8n/workflow-sdk';"]
for var,spec in nodes:
    raw=json.dumps(spec,ensure_ascii=False).replace('$','\\u0024').replace('{"name": "Zoho Calendar OAuth2"}',"newCredential('Zoho Calendar OAuth2')")
    lines.append('const '+var+' = '+('trigger' if spec['type'].endswith(('manualTrigger','scheduleTrigger')) else 'node')+'('+raw+');')
settings={'executionOrder':'v1','executionTimeout':120,'saveDataErrorExecution':'none','saveDataSuccessExecution':'none','saveExecutionProgress':False,'saveManualExecutions':False,'timezone':'Europe/Warsaw','callerPolicy':'workflowsFromSameOwner'}
lines.append("export default workflow('dona-zoho-calendar','DONA Panel — Zoho Calendar',"+json.dumps({'settings':settings})+").add(manual).to(config).to(calendars).to(select).to(events).to(normalize).to(save).to(report).add(schedule).to(config);")
(r/'backend/zoho.workflow.ts').write_text('\n'.join(lines));(r/'backend/zoho.nodes.json').write_text(json.dumps([{'name':n['config']['name'],'type':n['type'],'typeVersion':n['version'],'parameters':n['config']['parameters']} for _,n in nodes]))
