import { createHash } from 'node:crypto';
import { queueQuery } from './queries.mjs';

export const keySchemaSql = `CREATE TABLE IF NOT EXISTS pm_os.dona_router_pilot_keys_v1 (
 token_hash text PRIMARY KEY CHECK(token_hash ~ '^[a-f0-9]{64}$'),
 runner_id text NOT NULL, task_id text NOT NULL, context_hash text NOT NULL,
 project text NOT NULL DEFAULT 'dona-panel' CHECK(project='dona-panel'),
 expires_at timestamptz NOT NULL, revoked boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE pm_os.dona_router_pilot_keys_v1 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON pm_os.dona_router_pilot_keys_v1 FROM PUBLIC,anon,authenticated;`;

export function authenticateQuery(headers) {
  const match = /^Bearer ([a-f0-9]{64})$/.exec(headers?.authorization || '');
  if (!match) return null;
  const digest = createHash('sha256').update(match[1]).digest('hex');
  return { query: `SELECT EXISTS(SELECT 1 FROM pm_os.dona_router_pilot_keys_v1
    WHERE token_hash=$1 AND NOT revoked AND expires_at>now()) AS authorized,
    (SELECT row_to_json(k) FROM (SELECT runner_id,task_id,context_hash,project
      FROM pm_os.dona_router_pilot_keys_v1 WHERE token_hash=$1 AND NOT revoked AND expires_at>now()) k) AS scope;`,
    params: [digest] };
}

export function authorizedQuery(body, auth, digest) {
  if (auth?.authorized !== true || auth.scope?.project !== 'dona-panel') throw new Error('AUTH_FAILED');
  if (!/^[a-f0-9]{64}$/.test(digest || '')) throw new Error('AUTH_FAILED');
  if (!body || Array.isArray(body) || typeof body !== 'object' || Buffer.byteLength(JSON.stringify(body)) > 128 * 1024)
    throw new Error('INVALID_REQUEST');
  const scope = auth.scope;
  if (!['status','read','acquire','owns','renew','save','release'].includes(body.operation))
    throw new Error('OPERATION_NOT_ALLOWED');
  // Missing fields are rejected rather than silently widening the task scope.
  if (body.runnerId !== scope.runner_id || body.taskId !== scope.task_id || body.contextHash !== scope.context_hash)
    throw new Error('SCOPE_MISMATCH');
  if (body.operation === 'status') return { query: `SELECT EXISTS(SELECT 1 FROM pm_os.dona_router_pilot_keys_v1
    WHERE token_hash=$1 AND runner_id=$2 AND task_id=$3 AND context_hash=$4
      AND NOT revoked AND expires_at>now()) AS ok;`,
    params: [digest,scope.runner_id,scope.task_id,scope.context_hash] };
  const spec = queueQuery(body);
  const marker = 'WHERE task_id=$1 AND context_hash=$2';
  if (!spec.query.includes(marker)) throw new Error('UNGUARDED_QUERY');
  const guard = ` AND EXISTS(SELECT 1 FROM pm_os.dona_router_pilot_keys_v1 k
    WHERE k.token_hash=$${spec.params.length+1} AND k.runner_id=$${spec.params.length+2}
    AND k.task_id=$1 AND k.context_hash=$2 AND NOT k.revoked AND k.expires_at>now())`;
  // Fixed SQL generated by queueQuery, never SQL accepted from the request.
  return { query: spec.query.replaceAll(marker, marker + guard), params: [...spec.params,digest,scope.runner_id] };
}
